/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class AttributeDelete200ResponseResult {
  
  @SerializedName("deleted")
  private String deleted = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDeleted() {
    return deleted;
  }
  public void setDeleted(String deleted) {
    this.deleted = deleted;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttributeDelete200ResponseResult attributeDelete200ResponseResult = (AttributeDelete200ResponseResult) o;
    return (this.deleted == null ? attributeDelete200ResponseResult.deleted == null : this.deleted.equals(attributeDelete200ResponseResult.deleted));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.deleted == null ? 0: this.deleted.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttributeDelete200ResponseResult {\n");
    
    sb.append("  deleted: ").append(deleted).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
