/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.A2CDateTime;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class BatchJob {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("method")
  private String method = null;
  @SerializedName("status")
  private String status = null;
  @SerializedName("created_time")
  private A2CDateTime createdTime = null;
  @SerializedName("processed_time")
  private A2CDateTime processedTime = null;
  @SerializedName("additional_fields")
  private Object additionalFields = null;
  @SerializedName("custom_fields")
  private Object customFields = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMethod() {
    return method;
  }
  public void setMethod(String method) {
    this.method = method;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public A2CDateTime getCreatedTime() {
    return createdTime;
  }
  public void setCreatedTime(A2CDateTime createdTime) {
    this.createdTime = createdTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public A2CDateTime getProcessedTime() {
    return processedTime;
  }
  public void setProcessedTime(A2CDateTime processedTime) {
    this.processedTime = processedTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getAdditionalFields() {
    return additionalFields;
  }
  public void setAdditionalFields(Object additionalFields) {
    this.additionalFields = additionalFields;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getCustomFields() {
    return customFields;
  }
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchJob batchJob = (BatchJob) o;
    return (this.id == null ? batchJob.id == null : this.id.equals(batchJob.id)) &&
        (this.method == null ? batchJob.method == null : this.method.equals(batchJob.method)) &&
        (this.status == null ? batchJob.status == null : this.status.equals(batchJob.status)) &&
        (this.createdTime == null ? batchJob.createdTime == null : this.createdTime.equals(batchJob.createdTime)) &&
        (this.processedTime == null ? batchJob.processedTime == null : this.processedTime.equals(batchJob.processedTime)) &&
        (this.additionalFields == null ? batchJob.additionalFields == null : this.additionalFields.equals(batchJob.additionalFields)) &&
        (this.customFields == null ? batchJob.customFields == null : this.customFields.equals(batchJob.customFields));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.method == null ? 0: this.method.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.createdTime == null ? 0: this.createdTime.hashCode());
    result = 31 * result + (this.processedTime == null ? 0: this.processedTime.hashCode());
    result = 31 * result + (this.additionalFields == null ? 0: this.additionalFields.hashCode());
    result = 31 * result + (this.customFields == null ? 0: this.customFields.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchJob {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  method: ").append(method).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  createdTime: ").append(createdTime).append("\n");
    sb.append("  processedTime: ").append(processedTime).append("\n");
    sb.append("  additionalFields: ").append(additionalFields).append("\n");
    sb.append("  customFields: ").append(customFields).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
