/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.Image;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Brand {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("created_time")
  private String createdTime = null;
  @SerializedName("modified_time")
  private String modifiedTime = null;
  @SerializedName("full_description")
  private String fullDescription = null;
  @SerializedName("short_description")
  private String shortDescription = null;
  @SerializedName("stores_ids")
  private List<String> storesIds = null;
  @SerializedName("active")
  private Boolean active = null;
  @SerializedName("url")
  private String url = null;
  @SerializedName("meta_title")
  private String metaTitle = null;
  @SerializedName("meta_keywords")
  private String metaKeywords = null;
  @SerializedName("meta_description")
  private String metaDescription = null;
  @SerializedName("images")
  private List<Image> images = null;
  @SerializedName("additional_fields")
  private Object additionalFields = null;
  @SerializedName("custom_fields")
  private Object customFields = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCreatedTime() {
    return createdTime;
  }
  public void setCreatedTime(String createdTime) {
    this.createdTime = createdTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getModifiedTime() {
    return modifiedTime;
  }
  public void setModifiedTime(String modifiedTime) {
    this.modifiedTime = modifiedTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFullDescription() {
    return fullDescription;
  }
  public void setFullDescription(String fullDescription) {
    this.fullDescription = fullDescription;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getShortDescription() {
    return shortDescription;
  }
  public void setShortDescription(String shortDescription) {
    this.shortDescription = shortDescription;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getStoresIds() {
    return storesIds;
  }
  public void setStoresIds(List<String> storesIds) {
    this.storesIds = storesIds;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getActive() {
    return active;
  }
  public void setActive(Boolean active) {
    this.active = active;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMetaTitle() {
    return metaTitle;
  }
  public void setMetaTitle(String metaTitle) {
    this.metaTitle = metaTitle;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMetaKeywords() {
    return metaKeywords;
  }
  public void setMetaKeywords(String metaKeywords) {
    this.metaKeywords = metaKeywords;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMetaDescription() {
    return metaDescription;
  }
  public void setMetaDescription(String metaDescription) {
    this.metaDescription = metaDescription;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Image> getImages() {
    return images;
  }
  public void setImages(List<Image> images) {
    this.images = images;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getAdditionalFields() {
    return additionalFields;
  }
  public void setAdditionalFields(Object additionalFields) {
    this.additionalFields = additionalFields;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getCustomFields() {
    return customFields;
  }
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Brand brand = (Brand) o;
    return (this.id == null ? brand.id == null : this.id.equals(brand.id)) &&
        (this.name == null ? brand.name == null : this.name.equals(brand.name)) &&
        (this.createdTime == null ? brand.createdTime == null : this.createdTime.equals(brand.createdTime)) &&
        (this.modifiedTime == null ? brand.modifiedTime == null : this.modifiedTime.equals(brand.modifiedTime)) &&
        (this.fullDescription == null ? brand.fullDescription == null : this.fullDescription.equals(brand.fullDescription)) &&
        (this.shortDescription == null ? brand.shortDescription == null : this.shortDescription.equals(brand.shortDescription)) &&
        (this.storesIds == null ? brand.storesIds == null : this.storesIds.equals(brand.storesIds)) &&
        (this.active == null ? brand.active == null : this.active.equals(brand.active)) &&
        (this.url == null ? brand.url == null : this.url.equals(brand.url)) &&
        (this.metaTitle == null ? brand.metaTitle == null : this.metaTitle.equals(brand.metaTitle)) &&
        (this.metaKeywords == null ? brand.metaKeywords == null : this.metaKeywords.equals(brand.metaKeywords)) &&
        (this.metaDescription == null ? brand.metaDescription == null : this.metaDescription.equals(brand.metaDescription)) &&
        (this.images == null ? brand.images == null : this.images.equals(brand.images)) &&
        (this.additionalFields == null ? brand.additionalFields == null : this.additionalFields.equals(brand.additionalFields)) &&
        (this.customFields == null ? brand.customFields == null : this.customFields.equals(brand.customFields));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.createdTime == null ? 0: this.createdTime.hashCode());
    result = 31 * result + (this.modifiedTime == null ? 0: this.modifiedTime.hashCode());
    result = 31 * result + (this.fullDescription == null ? 0: this.fullDescription.hashCode());
    result = 31 * result + (this.shortDescription == null ? 0: this.shortDescription.hashCode());
    result = 31 * result + (this.storesIds == null ? 0: this.storesIds.hashCode());
    result = 31 * result + (this.active == null ? 0: this.active.hashCode());
    result = 31 * result + (this.url == null ? 0: this.url.hashCode());
    result = 31 * result + (this.metaTitle == null ? 0: this.metaTitle.hashCode());
    result = 31 * result + (this.metaKeywords == null ? 0: this.metaKeywords.hashCode());
    result = 31 * result + (this.metaDescription == null ? 0: this.metaDescription.hashCode());
    result = 31 * result + (this.images == null ? 0: this.images.hashCode());
    result = 31 * result + (this.additionalFields == null ? 0: this.additionalFields.hashCode());
    result = 31 * result + (this.customFields == null ? 0: this.customFields.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Brand {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  createdTime: ").append(createdTime).append("\n");
    sb.append("  modifiedTime: ").append(modifiedTime).append("\n");
    sb.append("  fullDescription: ").append(fullDescription).append("\n");
    sb.append("  shortDescription: ").append(shortDescription).append("\n");
    sb.append("  storesIds: ").append(storesIds).append("\n");
    sb.append("  active: ").append(active).append("\n");
    sb.append("  url: ").append(url).append("\n");
    sb.append("  metaTitle: ").append(metaTitle).append("\n");
    sb.append("  metaKeywords: ").append(metaKeywords).append("\n");
    sb.append("  metaDescription: ").append(metaDescription).append("\n");
    sb.append("  images: ").append(images).append("\n");
    sb.append("  additionalFields: ").append(additionalFields).append("\n");
    sb.append("  customFields: ").append(customFields).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
