/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CartShippingZone {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("code")
  private String code = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("country")
  private String country = null;
  @SerializedName("country_iso2_codes")
  private List<String> countryIso2Codes = null;
  @SerializedName("additional_fields")
  private Object additionalFields = null;
  @SerializedName("custom_fields")
  private Object customFields = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCode() {
    return code;
  }
  public void setCode(String code) {
    this.code = code;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCountry() {
    return country;
  }
  public void setCountry(String country) {
    this.country = country;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getCountryIso2Codes() {
    return countryIso2Codes;
  }
  public void setCountryIso2Codes(List<String> countryIso2Codes) {
    this.countryIso2Codes = countryIso2Codes;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getAdditionalFields() {
    return additionalFields;
  }
  public void setAdditionalFields(Object additionalFields) {
    this.additionalFields = additionalFields;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getCustomFields() {
    return customFields;
  }
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CartShippingZone cartShippingZone = (CartShippingZone) o;
    return (this.id == null ? cartShippingZone.id == null : this.id.equals(cartShippingZone.id)) &&
        (this.code == null ? cartShippingZone.code == null : this.code.equals(cartShippingZone.code)) &&
        (this.name == null ? cartShippingZone.name == null : this.name.equals(cartShippingZone.name)) &&
        (this.country == null ? cartShippingZone.country == null : this.country.equals(cartShippingZone.country)) &&
        (this.countryIso2Codes == null ? cartShippingZone.countryIso2Codes == null : this.countryIso2Codes.equals(cartShippingZone.countryIso2Codes)) &&
        (this.additionalFields == null ? cartShippingZone.additionalFields == null : this.additionalFields.equals(cartShippingZone.additionalFields)) &&
        (this.customFields == null ? cartShippingZone.customFields == null : this.customFields.equals(cartShippingZone.customFields));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.code == null ? 0: this.code.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.country == null ? 0: this.country.hashCode());
    result = 31 * result + (this.countryIso2Codes == null ? 0: this.countryIso2Codes.hashCode());
    result = 31 * result + (this.additionalFields == null ? 0: this.additionalFields.hashCode());
    result = 31 * result + (this.customFields == null ? 0: this.customFields.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CartShippingZone {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  code: ").append(code).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  country: ").append(country).append("\n");
    sb.append("  countryIso2Codes: ").append(countryIso2Codes).append("\n");
    sb.append("  additionalFields: ").append(additionalFields).append("\n");
    sb.append("  customFields: ").append(customFields).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
