/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CartCouponCount200ResponseResult {
  
  @SerializedName("coupons_count")
  private String couponsCount = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCouponsCount() {
    return couponsCount;
  }
  public void setCouponsCount(String couponsCount) {
    this.couponsCount = couponsCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CartCouponCount200ResponseResult cartCouponCount200ResponseResult = (CartCouponCount200ResponseResult) o;
    return (this.couponsCount == null ? cartCouponCount200ResponseResult.couponsCount == null : this.couponsCount.equals(cartCouponCount200ResponseResult.couponsCount));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.couponsCount == null ? 0: this.couponsCount.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CartCouponCount200ResponseResult {\n");
    
    sb.append("  couponsCount: ").append(couponsCount).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
