/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CategoryAddBatch200ResponseResult {
  
  @SerializedName("job_id")
  private String jobId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getJobId() {
    return jobId;
  }
  public void setJobId(String jobId) {
    this.jobId = jobId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CategoryAddBatch200ResponseResult categoryAddBatch200ResponseResult = (CategoryAddBatch200ResponseResult) o;
    return (this.jobId == null ? categoryAddBatch200ResponseResult.jobId == null : this.jobId.equals(categoryAddBatch200ResponseResult.jobId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.jobId == null ? 0: this.jobId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CategoryAddBatch200ResponseResult {\n");
    
    sb.append("  jobId: ").append(jobId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
