/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CouponCondition {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("entity")
  private String entity = null;
  @SerializedName("match_items")
  private String matchItems = null;
  @SerializedName("key")
  private String key = null;
  @SerializedName("operator")
  private String operator = null;
  @SerializedName("value")
  private String value = null;
  @SerializedName("logic_operator")
  private String logicOperator = null;
  @SerializedName("sub-conditions")
  private List<CouponCondition> subConditions = null;
  @SerializedName("additional_fields")
  private Object additionalFields = null;
  @SerializedName("custom_fields")
  private Object customFields = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEntity() {
    return entity;
  }
  public void setEntity(String entity) {
    this.entity = entity;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMatchItems() {
    return matchItems;
  }
  public void setMatchItems(String matchItems) {
    this.matchItems = matchItems;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getKey() {
    return key;
  }
  public void setKey(String key) {
    this.key = key;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOperator() {
    return operator;
  }
  public void setOperator(String operator) {
    this.operator = operator;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getValue() {
    return value;
  }
  public void setValue(String value) {
    this.value = value;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLogicOperator() {
    return logicOperator;
  }
  public void setLogicOperator(String logicOperator) {
    this.logicOperator = logicOperator;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<CouponCondition> getSubConditions() {
    return subConditions;
  }
  public void setSubConditions(List<CouponCondition> subConditions) {
    this.subConditions = subConditions;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getAdditionalFields() {
    return additionalFields;
  }
  public void setAdditionalFields(Object additionalFields) {
    this.additionalFields = additionalFields;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getCustomFields() {
    return customFields;
  }
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CouponCondition couponCondition = (CouponCondition) o;
    return (this.id == null ? couponCondition.id == null : this.id.equals(couponCondition.id)) &&
        (this.entity == null ? couponCondition.entity == null : this.entity.equals(couponCondition.entity)) &&
        (this.matchItems == null ? couponCondition.matchItems == null : this.matchItems.equals(couponCondition.matchItems)) &&
        (this.key == null ? couponCondition.key == null : this.key.equals(couponCondition.key)) &&
        (this.operator == null ? couponCondition.operator == null : this.operator.equals(couponCondition.operator)) &&
        (this.value == null ? couponCondition.value == null : this.value.equals(couponCondition.value)) &&
        (this.logicOperator == null ? couponCondition.logicOperator == null : this.logicOperator.equals(couponCondition.logicOperator)) &&
        (this.subConditions == null ? couponCondition.subConditions == null : this.subConditions.equals(couponCondition.subConditions)) &&
        (this.additionalFields == null ? couponCondition.additionalFields == null : this.additionalFields.equals(couponCondition.additionalFields)) &&
        (this.customFields == null ? couponCondition.customFields == null : this.customFields.equals(couponCondition.customFields));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.entity == null ? 0: this.entity.hashCode());
    result = 31 * result + (this.matchItems == null ? 0: this.matchItems.hashCode());
    result = 31 * result + (this.key == null ? 0: this.key.hashCode());
    result = 31 * result + (this.operator == null ? 0: this.operator.hashCode());
    result = 31 * result + (this.value == null ? 0: this.value.hashCode());
    result = 31 * result + (this.logicOperator == null ? 0: this.logicOperator.hashCode());
    result = 31 * result + (this.subConditions == null ? 0: this.subConditions.hashCode());
    result = 31 * result + (this.additionalFields == null ? 0: this.additionalFields.hashCode());
    result = 31 * result + (this.customFields == null ? 0: this.customFields.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CouponCondition {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  entity: ").append(entity).append("\n");
    sb.append("  matchItems: ").append(matchItems).append("\n");
    sb.append("  key: ").append(key).append("\n");
    sb.append("  operator: ").append(operator).append("\n");
    sb.append("  value: ").append(value).append("\n");
    sb.append("  logicOperator: ").append(logicOperator).append("\n");
    sb.append("  subConditions: ").append(subConditions).append("\n");
    sb.append("  additionalFields: ").append(additionalFields).append("\n");
    sb.append("  customFields: ").append(customFields).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
