/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.A2CDateTime;
import org.openapitools.client.model.CustomerAddress;
import org.openapitools.client.model.CustomerConsent;
import org.openapitools.client.model.CustomerGroup;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Customer {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("email")
  private String email = null;
  @SerializedName("first_name")
  private String firstName = null;
  @SerializedName("last_name")
  private String lastName = null;
  @SerializedName("phone")
  private String phone = null;
  @SerializedName("created_time")
  private A2CDateTime createdTime = null;
  @SerializedName("modified_time")
  private A2CDateTime modifiedTime = null;
  @SerializedName("group")
  private List<CustomerGroup> group = null;
  @SerializedName("login")
  private String login = null;
  @SerializedName("last_login")
  private A2CDateTime lastLogin = null;
  @SerializedName("birth_day")
  private A2CDateTime birthDay = null;
  @SerializedName("status")
  private String status = null;
  @SerializedName("news_letter_subscription")
  private Boolean newsLetterSubscription = null;
  @SerializedName("consents")
  private List<CustomerConsent> consents = null;
  @SerializedName("gender")
  private String gender = null;
  @SerializedName("stores_ids")
  private List<String> storesIds = null;
  @SerializedName("website")
  private String website = null;
  @SerializedName("fax")
  private String fax = null;
  @SerializedName("company")
  private String company = null;
  @SerializedName("ip_address")
  private String ipAddress = null;
  @SerializedName("address_book")
  private List<CustomerAddress> addressBook = null;
  @SerializedName("lang_id")
  private String langId = null;
  @SerializedName("orders_count")
  private Integer ordersCount = null;
  @SerializedName("last_order_id")
  private String lastOrderId = null;
  @SerializedName("additional_fields")
  private Object additionalFields = null;
  @SerializedName("custom_fields")
  private Object customFields = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPhone() {
    return phone;
  }
  public void setPhone(String phone) {
    this.phone = phone;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public A2CDateTime getCreatedTime() {
    return createdTime;
  }
  public void setCreatedTime(A2CDateTime createdTime) {
    this.createdTime = createdTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public A2CDateTime getModifiedTime() {
    return modifiedTime;
  }
  public void setModifiedTime(A2CDateTime modifiedTime) {
    this.modifiedTime = modifiedTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<CustomerGroup> getGroup() {
    return group;
  }
  public void setGroup(List<CustomerGroup> group) {
    this.group = group;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLogin() {
    return login;
  }
  public void setLogin(String login) {
    this.login = login;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public A2CDateTime getLastLogin() {
    return lastLogin;
  }
  public void setLastLogin(A2CDateTime lastLogin) {
    this.lastLogin = lastLogin;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public A2CDateTime getBirthDay() {
    return birthDay;
  }
  public void setBirthDay(A2CDateTime birthDay) {
    this.birthDay = birthDay;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getNewsLetterSubscription() {
    return newsLetterSubscription;
  }
  public void setNewsLetterSubscription(Boolean newsLetterSubscription) {
    this.newsLetterSubscription = newsLetterSubscription;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<CustomerConsent> getConsents() {
    return consents;
  }
  public void setConsents(List<CustomerConsent> consents) {
    this.consents = consents;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getGender() {
    return gender;
  }
  public void setGender(String gender) {
    this.gender = gender;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getStoresIds() {
    return storesIds;
  }
  public void setStoresIds(List<String> storesIds) {
    this.storesIds = storesIds;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getWebsite() {
    return website;
  }
  public void setWebsite(String website) {
    this.website = website;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFax() {
    return fax;
  }
  public void setFax(String fax) {
    this.fax = fax;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCompany() {
    return company;
  }
  public void setCompany(String company) {
    this.company = company;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getIpAddress() {
    return ipAddress;
  }
  public void setIpAddress(String ipAddress) {
    this.ipAddress = ipAddress;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<CustomerAddress> getAddressBook() {
    return addressBook;
  }
  public void setAddressBook(List<CustomerAddress> addressBook) {
    this.addressBook = addressBook;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLangId() {
    return langId;
  }
  public void setLangId(String langId) {
    this.langId = langId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getOrdersCount() {
    return ordersCount;
  }
  public void setOrdersCount(Integer ordersCount) {
    this.ordersCount = ordersCount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLastOrderId() {
    return lastOrderId;
  }
  public void setLastOrderId(String lastOrderId) {
    this.lastOrderId = lastOrderId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getAdditionalFields() {
    return additionalFields;
  }
  public void setAdditionalFields(Object additionalFields) {
    this.additionalFields = additionalFields;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getCustomFields() {
    return customFields;
  }
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Customer customer = (Customer) o;
    return (this.id == null ? customer.id == null : this.id.equals(customer.id)) &&
        (this.email == null ? customer.email == null : this.email.equals(customer.email)) &&
        (this.firstName == null ? customer.firstName == null : this.firstName.equals(customer.firstName)) &&
        (this.lastName == null ? customer.lastName == null : this.lastName.equals(customer.lastName)) &&
        (this.phone == null ? customer.phone == null : this.phone.equals(customer.phone)) &&
        (this.createdTime == null ? customer.createdTime == null : this.createdTime.equals(customer.createdTime)) &&
        (this.modifiedTime == null ? customer.modifiedTime == null : this.modifiedTime.equals(customer.modifiedTime)) &&
        (this.group == null ? customer.group == null : this.group.equals(customer.group)) &&
        (this.login == null ? customer.login == null : this.login.equals(customer.login)) &&
        (this.lastLogin == null ? customer.lastLogin == null : this.lastLogin.equals(customer.lastLogin)) &&
        (this.birthDay == null ? customer.birthDay == null : this.birthDay.equals(customer.birthDay)) &&
        (this.status == null ? customer.status == null : this.status.equals(customer.status)) &&
        (this.newsLetterSubscription == null ? customer.newsLetterSubscription == null : this.newsLetterSubscription.equals(customer.newsLetterSubscription)) &&
        (this.consents == null ? customer.consents == null : this.consents.equals(customer.consents)) &&
        (this.gender == null ? customer.gender == null : this.gender.equals(customer.gender)) &&
        (this.storesIds == null ? customer.storesIds == null : this.storesIds.equals(customer.storesIds)) &&
        (this.website == null ? customer.website == null : this.website.equals(customer.website)) &&
        (this.fax == null ? customer.fax == null : this.fax.equals(customer.fax)) &&
        (this.company == null ? customer.company == null : this.company.equals(customer.company)) &&
        (this.ipAddress == null ? customer.ipAddress == null : this.ipAddress.equals(customer.ipAddress)) &&
        (this.addressBook == null ? customer.addressBook == null : this.addressBook.equals(customer.addressBook)) &&
        (this.langId == null ? customer.langId == null : this.langId.equals(customer.langId)) &&
        (this.ordersCount == null ? customer.ordersCount == null : this.ordersCount.equals(customer.ordersCount)) &&
        (this.lastOrderId == null ? customer.lastOrderId == null : this.lastOrderId.equals(customer.lastOrderId)) &&
        (this.additionalFields == null ? customer.additionalFields == null : this.additionalFields.equals(customer.additionalFields)) &&
        (this.customFields == null ? customer.customFields == null : this.customFields.equals(customer.customFields));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.firstName == null ? 0: this.firstName.hashCode());
    result = 31 * result + (this.lastName == null ? 0: this.lastName.hashCode());
    result = 31 * result + (this.phone == null ? 0: this.phone.hashCode());
    result = 31 * result + (this.createdTime == null ? 0: this.createdTime.hashCode());
    result = 31 * result + (this.modifiedTime == null ? 0: this.modifiedTime.hashCode());
    result = 31 * result + (this.group == null ? 0: this.group.hashCode());
    result = 31 * result + (this.login == null ? 0: this.login.hashCode());
    result = 31 * result + (this.lastLogin == null ? 0: this.lastLogin.hashCode());
    result = 31 * result + (this.birthDay == null ? 0: this.birthDay.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.newsLetterSubscription == null ? 0: this.newsLetterSubscription.hashCode());
    result = 31 * result + (this.consents == null ? 0: this.consents.hashCode());
    result = 31 * result + (this.gender == null ? 0: this.gender.hashCode());
    result = 31 * result + (this.storesIds == null ? 0: this.storesIds.hashCode());
    result = 31 * result + (this.website == null ? 0: this.website.hashCode());
    result = 31 * result + (this.fax == null ? 0: this.fax.hashCode());
    result = 31 * result + (this.company == null ? 0: this.company.hashCode());
    result = 31 * result + (this.ipAddress == null ? 0: this.ipAddress.hashCode());
    result = 31 * result + (this.addressBook == null ? 0: this.addressBook.hashCode());
    result = 31 * result + (this.langId == null ? 0: this.langId.hashCode());
    result = 31 * result + (this.ordersCount == null ? 0: this.ordersCount.hashCode());
    result = 31 * result + (this.lastOrderId == null ? 0: this.lastOrderId.hashCode());
    result = 31 * result + (this.additionalFields == null ? 0: this.additionalFields.hashCode());
    result = 31 * result + (this.customFields == null ? 0: this.customFields.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Customer {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  firstName: ").append(firstName).append("\n");
    sb.append("  lastName: ").append(lastName).append("\n");
    sb.append("  phone: ").append(phone).append("\n");
    sb.append("  createdTime: ").append(createdTime).append("\n");
    sb.append("  modifiedTime: ").append(modifiedTime).append("\n");
    sb.append("  group: ").append(group).append("\n");
    sb.append("  login: ").append(login).append("\n");
    sb.append("  lastLogin: ").append(lastLogin).append("\n");
    sb.append("  birthDay: ").append(birthDay).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  newsLetterSubscription: ").append(newsLetterSubscription).append("\n");
    sb.append("  consents: ").append(consents).append("\n");
    sb.append("  gender: ").append(gender).append("\n");
    sb.append("  storesIds: ").append(storesIds).append("\n");
    sb.append("  website: ").append(website).append("\n");
    sb.append("  fax: ").append(fax).append("\n");
    sb.append("  company: ").append(company).append("\n");
    sb.append("  ipAddress: ").append(ipAddress).append("\n");
    sb.append("  addressBook: ").append(addressBook).append("\n");
    sb.append("  langId: ").append(langId).append("\n");
    sb.append("  ordersCount: ").append(ordersCount).append("\n");
    sb.append("  lastOrderId: ").append(lastOrderId).append("\n");
    sb.append("  additionalFields: ").append(additionalFields).append("\n");
    sb.append("  customFields: ").append(customFields).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
