/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.math.BigDecimal;
import java.util.*;
import org.openapitools.client.model.CouponHistory;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GiftCard {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("code")
  private String code = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("type")
  private String type = null;
  @SerializedName("currency_code")
  private String currencyCode = null;
  @SerializedName("amount")
  private BigDecimal amount = null;
  @SerializedName("initial_amount")
  private BigDecimal initialAmount = null;
  @SerializedName("status")
  private String status = null;
  @SerializedName("created_at")
  private String createdAt = null;
  @SerializedName("avail_to")
  private String availTo = null;
  @SerializedName("free_product_ids")
  private String freeProductIds = null;
  @SerializedName("message")
  private String message = null;
  @SerializedName("issuer_email")
  private String issuerEmail = null;
  @SerializedName("recipient_email")
  private String recipientEmail = null;
  @SerializedName("issuer_name")
  private String issuerName = null;
  @SerializedName("recipient_name")
  private String recipientName = null;
  @SerializedName("usage_history")
  private List<CouponHistory> usageHistory = null;
  @SerializedName("additional_fields")
  private Object additionalFields = null;
  @SerializedName("custom_fields")
  private Object customFields = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCode() {
    return code;
  }
  public void setCode(String code) {
    this.code = code;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCurrencyCode() {
    return currencyCode;
  }
  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getAmount() {
    return amount;
  }
  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getInitialAmount() {
    return initialAmount;
  }
  public void setInitialAmount(BigDecimal initialAmount) {
    this.initialAmount = initialAmount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAvailTo() {
    return availTo;
  }
  public void setAvailTo(String availTo) {
    this.availTo = availTo;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFreeProductIds() {
    return freeProductIds;
  }
  public void setFreeProductIds(String freeProductIds) {
    this.freeProductIds = freeProductIds;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }
  public void setMessage(String message) {
    this.message = message;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getIssuerEmail() {
    return issuerEmail;
  }
  public void setIssuerEmail(String issuerEmail) {
    this.issuerEmail = issuerEmail;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRecipientEmail() {
    return recipientEmail;
  }
  public void setRecipientEmail(String recipientEmail) {
    this.recipientEmail = recipientEmail;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getIssuerName() {
    return issuerName;
  }
  public void setIssuerName(String issuerName) {
    this.issuerName = issuerName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRecipientName() {
    return recipientName;
  }
  public void setRecipientName(String recipientName) {
    this.recipientName = recipientName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<CouponHistory> getUsageHistory() {
    return usageHistory;
  }
  public void setUsageHistory(List<CouponHistory> usageHistory) {
    this.usageHistory = usageHistory;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getAdditionalFields() {
    return additionalFields;
  }
  public void setAdditionalFields(Object additionalFields) {
    this.additionalFields = additionalFields;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getCustomFields() {
    return customFields;
  }
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GiftCard giftCard = (GiftCard) o;
    return (this.id == null ? giftCard.id == null : this.id.equals(giftCard.id)) &&
        (this.code == null ? giftCard.code == null : this.code.equals(giftCard.code)) &&
        (this.name == null ? giftCard.name == null : this.name.equals(giftCard.name)) &&
        (this.type == null ? giftCard.type == null : this.type.equals(giftCard.type)) &&
        (this.currencyCode == null ? giftCard.currencyCode == null : this.currencyCode.equals(giftCard.currencyCode)) &&
        (this.amount == null ? giftCard.amount == null : this.amount.equals(giftCard.amount)) &&
        (this.initialAmount == null ? giftCard.initialAmount == null : this.initialAmount.equals(giftCard.initialAmount)) &&
        (this.status == null ? giftCard.status == null : this.status.equals(giftCard.status)) &&
        (this.createdAt == null ? giftCard.createdAt == null : this.createdAt.equals(giftCard.createdAt)) &&
        (this.availTo == null ? giftCard.availTo == null : this.availTo.equals(giftCard.availTo)) &&
        (this.freeProductIds == null ? giftCard.freeProductIds == null : this.freeProductIds.equals(giftCard.freeProductIds)) &&
        (this.message == null ? giftCard.message == null : this.message.equals(giftCard.message)) &&
        (this.issuerEmail == null ? giftCard.issuerEmail == null : this.issuerEmail.equals(giftCard.issuerEmail)) &&
        (this.recipientEmail == null ? giftCard.recipientEmail == null : this.recipientEmail.equals(giftCard.recipientEmail)) &&
        (this.issuerName == null ? giftCard.issuerName == null : this.issuerName.equals(giftCard.issuerName)) &&
        (this.recipientName == null ? giftCard.recipientName == null : this.recipientName.equals(giftCard.recipientName)) &&
        (this.usageHistory == null ? giftCard.usageHistory == null : this.usageHistory.equals(giftCard.usageHistory)) &&
        (this.additionalFields == null ? giftCard.additionalFields == null : this.additionalFields.equals(giftCard.additionalFields)) &&
        (this.customFields == null ? giftCard.customFields == null : this.customFields.equals(giftCard.customFields));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.code == null ? 0: this.code.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.currencyCode == null ? 0: this.currencyCode.hashCode());
    result = 31 * result + (this.amount == null ? 0: this.amount.hashCode());
    result = 31 * result + (this.initialAmount == null ? 0: this.initialAmount.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.createdAt == null ? 0: this.createdAt.hashCode());
    result = 31 * result + (this.availTo == null ? 0: this.availTo.hashCode());
    result = 31 * result + (this.freeProductIds == null ? 0: this.freeProductIds.hashCode());
    result = 31 * result + (this.message == null ? 0: this.message.hashCode());
    result = 31 * result + (this.issuerEmail == null ? 0: this.issuerEmail.hashCode());
    result = 31 * result + (this.recipientEmail == null ? 0: this.recipientEmail.hashCode());
    result = 31 * result + (this.issuerName == null ? 0: this.issuerName.hashCode());
    result = 31 * result + (this.recipientName == null ? 0: this.recipientName.hashCode());
    result = 31 * result + (this.usageHistory == null ? 0: this.usageHistory.hashCode());
    result = 31 * result + (this.additionalFields == null ? 0: this.additionalFields.hashCode());
    result = 31 * result + (this.customFields == null ? 0: this.customFields.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GiftCard {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  code: ").append(code).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  currencyCode: ").append(currencyCode).append("\n");
    sb.append("  amount: ").append(amount).append("\n");
    sb.append("  initialAmount: ").append(initialAmount).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  createdAt: ").append(createdAt).append("\n");
    sb.append("  availTo: ").append(availTo).append("\n");
    sb.append("  freeProductIds: ").append(freeProductIds).append("\n");
    sb.append("  message: ").append(message).append("\n");
    sb.append("  issuerEmail: ").append(issuerEmail).append("\n");
    sb.append("  recipientEmail: ").append(recipientEmail).append("\n");
    sb.append("  issuerName: ").append(issuerName).append("\n");
    sb.append("  recipientName: ").append(recipientName).append("\n");
    sb.append("  usageHistory: ").append(usageHistory).append("\n");
    sb.append("  additionalFields: ").append(additionalFields).append("\n");
    sb.append("  customFields: ").append(customFields).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
