/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class OrderShipmentTrackingAdd200ResponseResult {
  
  @SerializedName("shipment_tracking_id")
  private String shipmentTrackingId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getShipmentTrackingId() {
    return shipmentTrackingId;
  }
  public void setShipmentTrackingId(String shipmentTrackingId) {
    this.shipmentTrackingId = shipmentTrackingId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderShipmentTrackingAdd200ResponseResult orderShipmentTrackingAdd200ResponseResult = (OrderShipmentTrackingAdd200ResponseResult) o;
    return (this.shipmentTrackingId == null ? orderShipmentTrackingAdd200ResponseResult.shipmentTrackingId == null : this.shipmentTrackingId.equals(orderShipmentTrackingAdd200ResponseResult.shipmentTrackingId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.shipmentTrackingId == null ? 0: this.shipmentTrackingId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderShipmentTrackingAdd200ResponseResult {\n");
    
    sb.append("  shipmentTrackingId: ").append(shipmentTrackingId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
