/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class OrderReturnAddOrderProductsInner {
  
  @SerializedName("order_product_id")
  private String orderProductId = null;
  @SerializedName("order_product_quantity")
  private Integer orderProductQuantity = null;
  @SerializedName("order_product_reason_id")
  private String orderProductReasonId = null;
  @SerializedName("order_product_action_id")
  private String orderProductActionId = null;
  @SerializedName("order_product_customer_comment")
  private String orderProductCustomerComment = null;
  @SerializedName("order_product_handling_status")
  private String orderProductHandlingStatus = null;
  @SerializedName("order_product_condition")
  private String orderProductCondition = null;
  @SerializedName("order_product_reason")
  private String orderProductReason = null;
  @SerializedName("order_product_status")
  private String orderProductStatus = null;

  /**
   * Defines which products from the order should be returned
   **/
  @ApiModelProperty(required = true, value = "Defines which products from the order should be returned")
  public String getOrderProductId() {
    return orderProductId;
  }
  public void setOrderProductId(String orderProductId) {
    this.orderProductId = orderProductId;
  }

  /**
   * Defines how many product units from the order should be returned
   **/
  @ApiModelProperty(required = true, value = "Defines how many product units from the order should be returned")
  public Integer getOrderProductQuantity() {
    return orderProductQuantity;
  }
  public void setOrderProductQuantity(Integer orderProductQuantity) {
    this.orderProductQuantity = orderProductQuantity;
  }

  /**
   * Defines the ID of the return reason
   **/
  @ApiModelProperty(required = true, value = "Defines the ID of the return reason")
  public String getOrderProductReasonId() {
    return orderProductReasonId;
  }
  public void setOrderProductReasonId(String orderProductReasonId) {
    this.orderProductReasonId = orderProductReasonId;
  }

  /**
   * Defines the ID of the return action
   **/
  @ApiModelProperty(required = true, value = "Defines the ID of the return action")
  public String getOrderProductActionId() {
    return orderProductActionId;
  }
  public void setOrderProductActionId(String orderProductActionId) {
    this.orderProductActionId = orderProductActionId;
  }

  /**
   * Defines the customer's comment for return
   **/
  @ApiModelProperty(value = "Defines the customer's comment for return")
  public String getOrderProductCustomerComment() {
    return orderProductCustomerComment;
  }
  public void setOrderProductCustomerComment(String orderProductCustomerComment) {
    this.orderProductCustomerComment = orderProductCustomerComment;
  }

  /**
   * Defines handling status
   **/
  @ApiModelProperty(value = "Defines handling status")
  public String getOrderProductHandlingStatus() {
    return orderProductHandlingStatus;
  }
  public void setOrderProductHandlingStatus(String orderProductHandlingStatus) {
    this.orderProductHandlingStatus = orderProductHandlingStatus;
  }

  /**
   * Defines the product condition
   **/
  @ApiModelProperty(value = "Defines the product condition")
  public String getOrderProductCondition() {
    return orderProductCondition;
  }
  public void setOrderProductCondition(String orderProductCondition) {
    this.orderProductCondition = orderProductCondition;
  }

  /**
   * Defines return reason
   **/
  @ApiModelProperty(value = "Defines return reason")
  public String getOrderProductReason() {
    return orderProductReason;
  }
  public void setOrderProductReason(String orderProductReason) {
    this.orderProductReason = orderProductReason;
  }

  /**
   * Defines product return status
   **/
  @ApiModelProperty(value = "Defines product return status")
  public String getOrderProductStatus() {
    return orderProductStatus;
  }
  public void setOrderProductStatus(String orderProductStatus) {
    this.orderProductStatus = orderProductStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderReturnAddOrderProductsInner orderReturnAddOrderProductsInner = (OrderReturnAddOrderProductsInner) o;
    return (this.orderProductId == null ? orderReturnAddOrderProductsInner.orderProductId == null : this.orderProductId.equals(orderReturnAddOrderProductsInner.orderProductId)) &&
        (this.orderProductQuantity == null ? orderReturnAddOrderProductsInner.orderProductQuantity == null : this.orderProductQuantity.equals(orderReturnAddOrderProductsInner.orderProductQuantity)) &&
        (this.orderProductReasonId == null ? orderReturnAddOrderProductsInner.orderProductReasonId == null : this.orderProductReasonId.equals(orderReturnAddOrderProductsInner.orderProductReasonId)) &&
        (this.orderProductActionId == null ? orderReturnAddOrderProductsInner.orderProductActionId == null : this.orderProductActionId.equals(orderReturnAddOrderProductsInner.orderProductActionId)) &&
        (this.orderProductCustomerComment == null ? orderReturnAddOrderProductsInner.orderProductCustomerComment == null : this.orderProductCustomerComment.equals(orderReturnAddOrderProductsInner.orderProductCustomerComment)) &&
        (this.orderProductHandlingStatus == null ? orderReturnAddOrderProductsInner.orderProductHandlingStatus == null : this.orderProductHandlingStatus.equals(orderReturnAddOrderProductsInner.orderProductHandlingStatus)) &&
        (this.orderProductCondition == null ? orderReturnAddOrderProductsInner.orderProductCondition == null : this.orderProductCondition.equals(orderReturnAddOrderProductsInner.orderProductCondition)) &&
        (this.orderProductReason == null ? orderReturnAddOrderProductsInner.orderProductReason == null : this.orderProductReason.equals(orderReturnAddOrderProductsInner.orderProductReason)) &&
        (this.orderProductStatus == null ? orderReturnAddOrderProductsInner.orderProductStatus == null : this.orderProductStatus.equals(orderReturnAddOrderProductsInner.orderProductStatus));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.orderProductId == null ? 0: this.orderProductId.hashCode());
    result = 31 * result + (this.orderProductQuantity == null ? 0: this.orderProductQuantity.hashCode());
    result = 31 * result + (this.orderProductReasonId == null ? 0: this.orderProductReasonId.hashCode());
    result = 31 * result + (this.orderProductActionId == null ? 0: this.orderProductActionId.hashCode());
    result = 31 * result + (this.orderProductCustomerComment == null ? 0: this.orderProductCustomerComment.hashCode());
    result = 31 * result + (this.orderProductHandlingStatus == null ? 0: this.orderProductHandlingStatus.hashCode());
    result = 31 * result + (this.orderProductCondition == null ? 0: this.orderProductCondition.hashCode());
    result = 31 * result + (this.orderProductReason == null ? 0: this.orderProductReason.hashCode());
    result = 31 * result + (this.orderProductStatus == null ? 0: this.orderProductStatus.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderReturnAddOrderProductsInner {\n");
    
    sb.append("  orderProductId: ").append(orderProductId).append("\n");
    sb.append("  orderProductQuantity: ").append(orderProductQuantity).append("\n");
    sb.append("  orderProductReasonId: ").append(orderProductReasonId).append("\n");
    sb.append("  orderProductActionId: ").append(orderProductActionId).append("\n");
    sb.append("  orderProductCustomerComment: ").append(orderProductCustomerComment).append("\n");
    sb.append("  orderProductHandlingStatus: ").append(orderProductHandlingStatus).append("\n");
    sb.append("  orderProductCondition: ").append(orderProductCondition).append("\n");
    sb.append("  orderProductReason: ").append(orderProductReason).append("\n");
    sb.append("  orderProductStatus: ").append(orderProductStatus).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
