/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.math.BigDecimal;
import java.util.*;
import org.openapitools.client.model.OrderItemOption;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class OrderCalculateBundle {
  
  @SerializedName("product_id")
  private String productId = null;
  @SerializedName("sku")
  private String sku = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("quantity")
  private Integer quantity = null;
  @SerializedName("price")
  private BigDecimal price = null;
  @SerializedName("price_inc_tax")
  private BigDecimal priceIncTax = null;
  @SerializedName("tax_rate")
  private BigDecimal taxRate = null;
  @SerializedName("unit_discount")
  private BigDecimal unitDiscount = null;
  @SerializedName("weight")
  private BigDecimal weight = null;
  @SerializedName("weight_unit")
  private String weightUnit = null;
  @SerializedName("barcode")
  private String barcode = null;
  @SerializedName("variant_id")
  private String variantId = null;
  @SerializedName("options")
  private List<OrderItemOption> options = null;
  @SerializedName("additional_fields")
  private Object additionalFields = null;
  @SerializedName("custom_fields")
  private Object customFields = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getProductId() {
    return productId;
  }
  public void setProductId(String productId) {
    this.productId = productId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSku() {
    return sku;
  }
  public void setSku(String sku) {
    this.sku = sku;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getQuantity() {
    return quantity;
  }
  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getPrice() {
    return price;
  }
  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getPriceIncTax() {
    return priceIncTax;
  }
  public void setPriceIncTax(BigDecimal priceIncTax) {
    this.priceIncTax = priceIncTax;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getTaxRate() {
    return taxRate;
  }
  public void setTaxRate(BigDecimal taxRate) {
    this.taxRate = taxRate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getUnitDiscount() {
    return unitDiscount;
  }
  public void setUnitDiscount(BigDecimal unitDiscount) {
    this.unitDiscount = unitDiscount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getWeight() {
    return weight;
  }
  public void setWeight(BigDecimal weight) {
    this.weight = weight;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getWeightUnit() {
    return weightUnit;
  }
  public void setWeightUnit(String weightUnit) {
    this.weightUnit = weightUnit;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getBarcode() {
    return barcode;
  }
  public void setBarcode(String barcode) {
    this.barcode = barcode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getVariantId() {
    return variantId;
  }
  public void setVariantId(String variantId) {
    this.variantId = variantId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<OrderItemOption> getOptions() {
    return options;
  }
  public void setOptions(List<OrderItemOption> options) {
    this.options = options;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getAdditionalFields() {
    return additionalFields;
  }
  public void setAdditionalFields(Object additionalFields) {
    this.additionalFields = additionalFields;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getCustomFields() {
    return customFields;
  }
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderCalculateBundle orderCalculateBundle = (OrderCalculateBundle) o;
    return (this.productId == null ? orderCalculateBundle.productId == null : this.productId.equals(orderCalculateBundle.productId)) &&
        (this.sku == null ? orderCalculateBundle.sku == null : this.sku.equals(orderCalculateBundle.sku)) &&
        (this.name == null ? orderCalculateBundle.name == null : this.name.equals(orderCalculateBundle.name)) &&
        (this.quantity == null ? orderCalculateBundle.quantity == null : this.quantity.equals(orderCalculateBundle.quantity)) &&
        (this.price == null ? orderCalculateBundle.price == null : this.price.equals(orderCalculateBundle.price)) &&
        (this.priceIncTax == null ? orderCalculateBundle.priceIncTax == null : this.priceIncTax.equals(orderCalculateBundle.priceIncTax)) &&
        (this.taxRate == null ? orderCalculateBundle.taxRate == null : this.taxRate.equals(orderCalculateBundle.taxRate)) &&
        (this.unitDiscount == null ? orderCalculateBundle.unitDiscount == null : this.unitDiscount.equals(orderCalculateBundle.unitDiscount)) &&
        (this.weight == null ? orderCalculateBundle.weight == null : this.weight.equals(orderCalculateBundle.weight)) &&
        (this.weightUnit == null ? orderCalculateBundle.weightUnit == null : this.weightUnit.equals(orderCalculateBundle.weightUnit)) &&
        (this.barcode == null ? orderCalculateBundle.barcode == null : this.barcode.equals(orderCalculateBundle.barcode)) &&
        (this.variantId == null ? orderCalculateBundle.variantId == null : this.variantId.equals(orderCalculateBundle.variantId)) &&
        (this.options == null ? orderCalculateBundle.options == null : this.options.equals(orderCalculateBundle.options)) &&
        (this.additionalFields == null ? orderCalculateBundle.additionalFields == null : this.additionalFields.equals(orderCalculateBundle.additionalFields)) &&
        (this.customFields == null ? orderCalculateBundle.customFields == null : this.customFields.equals(orderCalculateBundle.customFields));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.productId == null ? 0: this.productId.hashCode());
    result = 31 * result + (this.sku == null ? 0: this.sku.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.quantity == null ? 0: this.quantity.hashCode());
    result = 31 * result + (this.price == null ? 0: this.price.hashCode());
    result = 31 * result + (this.priceIncTax == null ? 0: this.priceIncTax.hashCode());
    result = 31 * result + (this.taxRate == null ? 0: this.taxRate.hashCode());
    result = 31 * result + (this.unitDiscount == null ? 0: this.unitDiscount.hashCode());
    result = 31 * result + (this.weight == null ? 0: this.weight.hashCode());
    result = 31 * result + (this.weightUnit == null ? 0: this.weightUnit.hashCode());
    result = 31 * result + (this.barcode == null ? 0: this.barcode.hashCode());
    result = 31 * result + (this.variantId == null ? 0: this.variantId.hashCode());
    result = 31 * result + (this.options == null ? 0: this.options.hashCode());
    result = 31 * result + (this.additionalFields == null ? 0: this.additionalFields.hashCode());
    result = 31 * result + (this.customFields == null ? 0: this.customFields.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderCalculateBundle {\n");
    
    sb.append("  productId: ").append(productId).append("\n");
    sb.append("  sku: ").append(sku).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  quantity: ").append(quantity).append("\n");
    sb.append("  price: ").append(price).append("\n");
    sb.append("  priceIncTax: ").append(priceIncTax).append("\n");
    sb.append("  taxRate: ").append(taxRate).append("\n");
    sb.append("  unitDiscount: ").append(unitDiscount).append("\n");
    sb.append("  weight: ").append(weight).append("\n");
    sb.append("  weightUnit: ").append(weightUnit).append("\n");
    sb.append("  barcode: ").append(barcode).append("\n");
    sb.append("  variantId: ").append(variantId).append("\n");
    sb.append("  options: ").append(options).append("\n");
    sb.append("  additionalFields: ").append(additionalFields).append("\n");
    sb.append("  customFields: ").append(customFields).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
