/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class OrderShipmentAddItemsInner {
  
  @SerializedName("order_product_id")
  private String orderProductId = null;
  @SerializedName("quantity")
  private BigDecimal quantity = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOrderProductId() {
    return orderProductId;
  }
  public void setOrderProductId(String orderProductId) {
    this.orderProductId = orderProductId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getQuantity() {
    return quantity;
  }
  public void setQuantity(BigDecimal quantity) {
    this.quantity = quantity;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderShipmentAddItemsInner orderShipmentAddItemsInner = (OrderShipmentAddItemsInner) o;
    return (this.orderProductId == null ? orderShipmentAddItemsInner.orderProductId == null : this.orderProductId.equals(orderShipmentAddItemsInner.orderProductId)) &&
        (this.quantity == null ? orderShipmentAddItemsInner.quantity == null : this.quantity.equals(orderShipmentAddItemsInner.quantity));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.orderProductId == null ? 0: this.orderProductId.hashCode());
    result = 31 * result + (this.quantity == null ? 0: this.quantity.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderShipmentAddItemsInner {\n");
    
    sb.append("  orderProductId: ").append(orderProductId).append("\n");
    sb.append("  quantity: ").append(quantity).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
