/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.A2CDateTime;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class OrderStatusHistoryItem {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("modified_time")
  private A2CDateTime modifiedTime = null;
  @SerializedName("notify")
  private Boolean notify = null;
  @SerializedName("comment")
  private String comment = null;
  @SerializedName("additional_fields")
  private Object additionalFields = null;
  @SerializedName("custom_fields")
  private Object customFields = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public A2CDateTime getModifiedTime() {
    return modifiedTime;
  }
  public void setModifiedTime(A2CDateTime modifiedTime) {
    this.modifiedTime = modifiedTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getNotify() {
    return notify;
  }
  public void setNotify(Boolean notify) {
    this.notify = notify;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getComment() {
    return comment;
  }
  public void setComment(String comment) {
    this.comment = comment;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getAdditionalFields() {
    return additionalFields;
  }
  public void setAdditionalFields(Object additionalFields) {
    this.additionalFields = additionalFields;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getCustomFields() {
    return customFields;
  }
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderStatusHistoryItem orderStatusHistoryItem = (OrderStatusHistoryItem) o;
    return (this.id == null ? orderStatusHistoryItem.id == null : this.id.equals(orderStatusHistoryItem.id)) &&
        (this.name == null ? orderStatusHistoryItem.name == null : this.name.equals(orderStatusHistoryItem.name)) &&
        (this.modifiedTime == null ? orderStatusHistoryItem.modifiedTime == null : this.modifiedTime.equals(orderStatusHistoryItem.modifiedTime)) &&
        (this.notify == null ? orderStatusHistoryItem.notify == null : this.notify.equals(orderStatusHistoryItem.notify)) &&
        (this.comment == null ? orderStatusHistoryItem.comment == null : this.comment.equals(orderStatusHistoryItem.comment)) &&
        (this.additionalFields == null ? orderStatusHistoryItem.additionalFields == null : this.additionalFields.equals(orderStatusHistoryItem.additionalFields)) &&
        (this.customFields == null ? orderStatusHistoryItem.customFields == null : this.customFields.equals(orderStatusHistoryItem.customFields));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.modifiedTime == null ? 0: this.modifiedTime.hashCode());
    result = 31 * result + (this.notify == null ? 0: this.notify.hashCode());
    result = 31 * result + (this.comment == null ? 0: this.comment.hashCode());
    result = 31 * result + (this.additionalFields == null ? 0: this.additionalFields.hashCode());
    result = 31 * result + (this.customFields == null ? 0: this.customFields.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderStatusHistoryItem {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  modifiedTime: ").append(modifiedTime).append("\n");
    sb.append("  notify: ").append(notify).append("\n");
    sb.append("  comment: ").append(comment).append("\n");
    sb.append("  additionalFields: ").append(additionalFields).append("\n");
    sb.append("  customFields: ").append(customFields).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
