/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class OrderShipmentTrackingAdd {
  
  @SerializedName("order_id")
  private String orderId = null;
  @SerializedName("shipment_id")
  private String shipmentId = null;
  @SerializedName("carrier_id")
  private String carrierId = null;
  @SerializedName("store_id")
  private String storeId = null;
  @SerializedName("tracking_provider")
  private String trackingProvider = null;
  @SerializedName("tracking_number")
  private String trackingNumber = null;
  @SerializedName("tracking_link")
  private String trackingLink = null;
  @SerializedName("send_notifications")
  private Boolean sendNotifications = false;

  /**
   * Defines the order id
   **/
  @ApiModelProperty(value = "Defines the order id")
  public String getOrderId() {
    return orderId;
  }
  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  /**
   * Shipment id indicates the number of delivery
   **/
  @ApiModelProperty(required = true, value = "Shipment id indicates the number of delivery")
  public String getShipmentId() {
    return shipmentId;
  }
  public void setShipmentId(String shipmentId) {
    this.shipmentId = shipmentId;
  }

  /**
   * Defines tracking carrier id
   **/
  @ApiModelProperty(value = "Defines tracking carrier id")
  public String getCarrierId() {
    return carrierId;
  }
  public void setCarrierId(String carrierId) {
    this.carrierId = carrierId;
  }

  /**
   * Store Id
   **/
  @ApiModelProperty(value = "Store Id")
  public String getStoreId() {
    return storeId;
  }
  public void setStoreId(String storeId) {
    this.storeId = storeId;
  }

  /**
   * Defines name of the company which provides shipment tracking
   **/
  @ApiModelProperty(value = "Defines name of the company which provides shipment tracking")
  public String getTrackingProvider() {
    return trackingProvider;
  }
  public void setTrackingProvider(String trackingProvider) {
    this.trackingProvider = trackingProvider;
  }

  /**
   * Defines tracking number
   **/
  @ApiModelProperty(required = true, value = "Defines tracking number")
  public String getTrackingNumber() {
    return trackingNumber;
  }
  public void setTrackingNumber(String trackingNumber) {
    this.trackingNumber = trackingNumber;
  }

  /**
   * Defines custom tracking link
   **/
  @ApiModelProperty(value = "Defines custom tracking link")
  public String getTrackingLink() {
    return trackingLink;
  }
  public void setTrackingLink(String trackingLink) {
    this.trackingLink = trackingLink;
  }

  /**
   * Send notifications to customer after tracking was created
   **/
  @ApiModelProperty(value = "Send notifications to customer after tracking was created")
  public Boolean getSendNotifications() {
    return sendNotifications;
  }
  public void setSendNotifications(Boolean sendNotifications) {
    this.sendNotifications = sendNotifications;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderShipmentTrackingAdd orderShipmentTrackingAdd = (OrderShipmentTrackingAdd) o;
    return (this.orderId == null ? orderShipmentTrackingAdd.orderId == null : this.orderId.equals(orderShipmentTrackingAdd.orderId)) &&
        (this.shipmentId == null ? orderShipmentTrackingAdd.shipmentId == null : this.shipmentId.equals(orderShipmentTrackingAdd.shipmentId)) &&
        (this.carrierId == null ? orderShipmentTrackingAdd.carrierId == null : this.carrierId.equals(orderShipmentTrackingAdd.carrierId)) &&
        (this.storeId == null ? orderShipmentTrackingAdd.storeId == null : this.storeId.equals(orderShipmentTrackingAdd.storeId)) &&
        (this.trackingProvider == null ? orderShipmentTrackingAdd.trackingProvider == null : this.trackingProvider.equals(orderShipmentTrackingAdd.trackingProvider)) &&
        (this.trackingNumber == null ? orderShipmentTrackingAdd.trackingNumber == null : this.trackingNumber.equals(orderShipmentTrackingAdd.trackingNumber)) &&
        (this.trackingLink == null ? orderShipmentTrackingAdd.trackingLink == null : this.trackingLink.equals(orderShipmentTrackingAdd.trackingLink)) &&
        (this.sendNotifications == null ? orderShipmentTrackingAdd.sendNotifications == null : this.sendNotifications.equals(orderShipmentTrackingAdd.sendNotifications));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.orderId == null ? 0: this.orderId.hashCode());
    result = 31 * result + (this.shipmentId == null ? 0: this.shipmentId.hashCode());
    result = 31 * result + (this.carrierId == null ? 0: this.carrierId.hashCode());
    result = 31 * result + (this.storeId == null ? 0: this.storeId.hashCode());
    result = 31 * result + (this.trackingProvider == null ? 0: this.trackingProvider.hashCode());
    result = 31 * result + (this.trackingNumber == null ? 0: this.trackingNumber.hashCode());
    result = 31 * result + (this.trackingLink == null ? 0: this.trackingLink.hashCode());
    result = 31 * result + (this.sendNotifications == null ? 0: this.sendNotifications.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderShipmentTrackingAdd {\n");
    
    sb.append("  orderId: ").append(orderId).append("\n");
    sb.append("  shipmentId: ").append(shipmentId).append("\n");
    sb.append("  carrierId: ").append(carrierId).append("\n");
    sb.append("  storeId: ").append(storeId).append("\n");
    sb.append("  trackingProvider: ").append(trackingProvider).append("\n");
    sb.append("  trackingNumber: ").append(trackingNumber).append("\n");
    sb.append("  trackingLink: ").append(trackingLink).append("\n");
    sb.append("  sendNotifications: ").append(sendNotifications).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
