/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.ProductFind200ResponseResultProductInner;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ProductFind200ResponseResult {
  
  @SerializedName("product")
  private List<ProductFind200ResponseResultProductInner> product = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<ProductFind200ResponseResultProductInner> getProduct() {
    return product;
  }
  public void setProduct(List<ProductFind200ResponseResultProductInner> product) {
    this.product = product;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductFind200ResponseResult productFind200ResponseResult = (ProductFind200ResponseResult) o;
    return (this.product == null ? productFind200ResponseResult.product == null : this.product.equals(productFind200ResponseResult.product));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.product == null ? 0: this.product.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductFind200ResponseResult {\n");
    
    sb.append("  product: ").append(product).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
