/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ProductOptionAdd200ResponseResult {
  
  @SerializedName("option_id")
  private String optionId = null;
  @SerializedName("product_option_id")
  private String productOptionId = null;
  @SerializedName("product_value_ids")
  private String productValueIds = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOptionId() {
    return optionId;
  }
  public void setOptionId(String optionId) {
    this.optionId = optionId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getProductOptionId() {
    return productOptionId;
  }
  public void setProductOptionId(String productOptionId) {
    this.productOptionId = productOptionId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getProductValueIds() {
    return productValueIds;
  }
  public void setProductValueIds(String productValueIds) {
    this.productValueIds = productValueIds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductOptionAdd200ResponseResult productOptionAdd200ResponseResult = (ProductOptionAdd200ResponseResult) o;
    return (this.optionId == null ? productOptionAdd200ResponseResult.optionId == null : this.optionId.equals(productOptionAdd200ResponseResult.optionId)) &&
        (this.productOptionId == null ? productOptionAdd200ResponseResult.productOptionId == null : this.productOptionId.equals(productOptionAdd200ResponseResult.productOptionId)) &&
        (this.productValueIds == null ? productOptionAdd200ResponseResult.productValueIds == null : this.productValueIds.equals(productOptionAdd200ResponseResult.productValueIds));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.optionId == null ? 0: this.optionId.hashCode());
    result = 31 * result + (this.productOptionId == null ? 0: this.productOptionId.hashCode());
    result = 31 * result + (this.productValueIds == null ? 0: this.productValueIds.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductOptionAdd200ResponseResult {\n");
    
    sb.append("  optionId: ").append(optionId).append("\n");
    sb.append("  productOptionId: ").append(productOptionId).append("\n");
    sb.append("  productValueIds: ").append(productValueIds).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
