/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ProductAddSpecificsInnerBookingDetailsAvailabilitiesInnerTimesInner {
  
  @SerializedName("from")
  private String from = null;
  @SerializedName("to")
  private String to = null;

  /**
   * The starting time of the of available booking slot in 24 hours format. Required if <code>type=date_time</code>
   **/
  @ApiModelProperty(required = true, value = "The starting time of the of available booking slot in 24 hours format. Required if <code>type=date_time</code>")
  public String getFrom() {
    return from;
  }
  public void setFrom(String from) {
    this.from = from;
  }

  /**
   * The ending time of the of available booking slot in 24 hours format. Required if <code>type=date_time</code>
   **/
  @ApiModelProperty(required = true, value = "The ending time of the of available booking slot in 24 hours format. Required if <code>type=date_time</code>")
  public String getTo() {
    return to;
  }
  public void setTo(String to) {
    this.to = to;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductAddSpecificsInnerBookingDetailsAvailabilitiesInnerTimesInner productAddSpecificsInnerBookingDetailsAvailabilitiesInnerTimesInner = (ProductAddSpecificsInnerBookingDetailsAvailabilitiesInnerTimesInner) o;
    return (this.from == null ? productAddSpecificsInnerBookingDetailsAvailabilitiesInnerTimesInner.from == null : this.from.equals(productAddSpecificsInnerBookingDetailsAvailabilitiesInnerTimesInner.from)) &&
        (this.to == null ? productAddSpecificsInnerBookingDetailsAvailabilitiesInnerTimesInner.to == null : this.to.equals(productAddSpecificsInnerBookingDetailsAvailabilitiesInnerTimesInner.to));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.from == null ? 0: this.from.hashCode());
    result = 31 * result + (this.to == null ? 0: this.to.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductAddSpecificsInnerBookingDetailsAvailabilitiesInnerTimesInner {\n");
    
    sb.append("  from: ").append(from).append("\n");
    sb.append("  to: ").append(to).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
