/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ProductCurrencyAdd200ResponseResult {
  
  @SerializedName("currency_id")
  private String currencyId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCurrencyId() {
    return currencyId;
  }
  public void setCurrencyId(String currencyId) {
    this.currencyId = currencyId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductCurrencyAdd200ResponseResult productCurrencyAdd200ResponseResult = (ProductCurrencyAdd200ResponseResult) o;
    return (this.currencyId == null ? productCurrencyAdd200ResponseResult.currencyId == null : this.currencyId.equals(productCurrencyAdd200ResponseResult.currencyId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.currencyId == null ? 0: this.currencyId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductCurrencyAdd200ResponseResult {\n");
    
    sb.append("  currencyId: ").append(currencyId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
