/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.OasAnyTypeNotMapped;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ProductChildItemFind200ResponseResult {
  
  @SerializedName("children")
  private OasAnyTypeNotMapped children = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public OasAnyTypeNotMapped getChildren() {
    return children;
  }
  public void setChildren(OasAnyTypeNotMapped children) {
    this.children = children;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductChildItemFind200ResponseResult productChildItemFind200ResponseResult = (ProductChildItemFind200ResponseResult) o;
    return (this.children == null ? productChildItemFind200ResponseResult.children == null : this.children.equals(productChildItemFind200ResponseResult.children));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.children == null ? 0: this.children.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductChildItemFind200ResponseResult {\n");
    
    sb.append("  children: ").append(children).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
