/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ProductGroupItem {
  
  @SerializedName("child_item_id")
  private String childItemId = null;
  @SerializedName("product_id")
  private String productId = null;
  @SerializedName("default_qty_in_pack")
  private String defaultQtyInPack = null;
  @SerializedName("is_qty_in_pack_fixed")
  private Boolean isQtyInPackFixed = null;
  @SerializedName("price")
  private BigDecimal price = null;
  @SerializedName("additional_fields")
  private Object additionalFields = null;
  @SerializedName("custom_fields")
  private Object customFields = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getChildItemId() {
    return childItemId;
  }
  public void setChildItemId(String childItemId) {
    this.childItemId = childItemId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getProductId() {
    return productId;
  }
  public void setProductId(String productId) {
    this.productId = productId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDefaultQtyInPack() {
    return defaultQtyInPack;
  }
  public void setDefaultQtyInPack(String defaultQtyInPack) {
    this.defaultQtyInPack = defaultQtyInPack;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getIsQtyInPackFixed() {
    return isQtyInPackFixed;
  }
  public void setIsQtyInPackFixed(Boolean isQtyInPackFixed) {
    this.isQtyInPackFixed = isQtyInPackFixed;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getPrice() {
    return price;
  }
  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getAdditionalFields() {
    return additionalFields;
  }
  public void setAdditionalFields(Object additionalFields) {
    this.additionalFields = additionalFields;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getCustomFields() {
    return customFields;
  }
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductGroupItem productGroupItem = (ProductGroupItem) o;
    return (this.childItemId == null ? productGroupItem.childItemId == null : this.childItemId.equals(productGroupItem.childItemId)) &&
        (this.productId == null ? productGroupItem.productId == null : this.productId.equals(productGroupItem.productId)) &&
        (this.defaultQtyInPack == null ? productGroupItem.defaultQtyInPack == null : this.defaultQtyInPack.equals(productGroupItem.defaultQtyInPack)) &&
        (this.isQtyInPackFixed == null ? productGroupItem.isQtyInPackFixed == null : this.isQtyInPackFixed.equals(productGroupItem.isQtyInPackFixed)) &&
        (this.price == null ? productGroupItem.price == null : this.price.equals(productGroupItem.price)) &&
        (this.additionalFields == null ? productGroupItem.additionalFields == null : this.additionalFields.equals(productGroupItem.additionalFields)) &&
        (this.customFields == null ? productGroupItem.customFields == null : this.customFields.equals(productGroupItem.customFields));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.childItemId == null ? 0: this.childItemId.hashCode());
    result = 31 * result + (this.productId == null ? 0: this.productId.hashCode());
    result = 31 * result + (this.defaultQtyInPack == null ? 0: this.defaultQtyInPack.hashCode());
    result = 31 * result + (this.isQtyInPackFixed == null ? 0: this.isQtyInPackFixed.hashCode());
    result = 31 * result + (this.price == null ? 0: this.price.hashCode());
    result = 31 * result + (this.additionalFields == null ? 0: this.additionalFields.hashCode());
    result = 31 * result + (this.customFields == null ? 0: this.customFields.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductGroupItem {\n");
    
    sb.append("  childItemId: ").append(childItemId).append("\n");
    sb.append("  productId: ").append(productId).append("\n");
    sb.append("  defaultQtyInPack: ").append(defaultQtyInPack).append("\n");
    sb.append("  isQtyInPackFixed: ").append(isQtyInPackFixed).append("\n");
    sb.append("  price: ").append(price).append("\n");
    sb.append("  additionalFields: ").append(additionalFields).append("\n");
    sb.append("  customFields: ").append(customFields).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
