/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * A size chart for the product. Only one property is supported.
 **/
@ApiModel(description = "A size chart for the product. Only one property is supported.")
public class ProductAddSizeChart {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("url")
  private String url = null;

  /**
   * Defines a pre-generated size chart template
   **/
  @ApiModelProperty(value = "Defines a pre-generated size chart template")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   * Defines a size chart image URL
   **/
  @ApiModelProperty(value = "Defines a size chart image URL")
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductAddSizeChart productAddSizeChart = (ProductAddSizeChart) o;
    return (this.id == null ? productAddSizeChart.id == null : this.id.equals(productAddSizeChart.id)) &&
        (this.url == null ? productAddSizeChart.url == null : this.url.equals(productAddSizeChart.url));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.url == null ? 0: this.url.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductAddSizeChart {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  url: ").append(url).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
