/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * If the seller is subscribed to \&quot;Business Policies\&quot;, use the seller_profiles instead of the shipping_details, payment_methods and return_accepted params.&lt;hr&gt;&lt;div style&#x3D;\&quot;font-style:normal\&quot;&gt;Param structure:&lt;div style&#x3D;\&quot;margin-left: 2%;\&quot;&gt;&lt;code style&#x3D;\&quot;padding:0; background-color:#ffffff;font-size:85%;font-family:monospace;\&quot;&gt;package_details[&lt;b&gt;measure_unit&lt;/b&gt;] &#x3D; string&lt;/br&gt; Allowed measure_unit values: [English or Metric] &lt;/br&gt; Default: Metric&lt;/br&gt;package_details[&lt;b&gt;weigh_unit&lt;/b&gt;] &#x3D; string&lt;/br&gt; Allowed weigh_unit values: [kg, g, lbs, oz]&lt;/br&gt;package_details[&lt;b&gt;package_depth&lt;/b&gt;] &#x3D; decimal&lt;/br&gt;package_details[&lt;b&gt;package_length&lt;/b&gt;] &#x3D; decimal&lt;/br&gt;package_details[&lt;b&gt;package_width&lt;/b&gt;] &#x3D; decimal&lt;/br&gt;package_details[&lt;b&gt;weight_major&lt;/b&gt;] &#x3D; decimal&lt;/br&gt;package_details[&lt;b&gt;weight_minor&lt;/b&gt;] &#x3D; decimal&lt;/br&gt;package_details[&lt;b&gt;shipping_package&lt;/b&gt;] &#x3D; string&lt;/br&gt; See cart.info method, param &#x60;eBay_shipping_package_details&#x60;&lt;/code&gt;&lt;/div&gt;&lt;/div&gt;
 **/
@ApiModel(description = "If the seller is subscribed to \"Business Policies\", use the seller_profiles instead of the shipping_details, payment_methods and return_accepted params.<hr><div style=\"font-style:normal\">Param structure:<div style=\"margin-left: 2%;\"><code style=\"padding:0; background-color:#ffffff;font-size:85%;font-family:monospace;\">package_details[<b>measure_unit</b>] = string</br> Allowed measure_unit values: [English or Metric] </br> Default: Metric</br>package_details[<b>weigh_unit</b>] = string</br> Allowed weigh_unit values: [kg, g, lbs, oz]</br>package_details[<b>package_depth</b>] = decimal</br>package_details[<b>package_length</b>] = decimal</br>package_details[<b>package_width</b>] = decimal</br>package_details[<b>weight_major</b>] = decimal</br>package_details[<b>weight_minor</b>] = decimal</br>package_details[<b>shipping_package</b>] = string</br> See cart.info method, param `eBay_shipping_package_details`</code></div></div>")
public class ProductAddPackageDetails {
  
  @SerializedName("measure_unit")
  private String measureUnit = null;
  @SerializedName("weigh_unit")
  private String weighUnit = null;
  @SerializedName("package_depth")
  private BigDecimal packageDepth = null;
  @SerializedName("package_length")
  private BigDecimal packageLength = null;
  @SerializedName("package_width")
  private BigDecimal packageWidth = null;
  @SerializedName("weight_major")
  private BigDecimal weightMajor = null;
  @SerializedName("weight_minor")
  private BigDecimal weightMinor = null;
  @SerializedName("shipping_package")
  private String shippingPackage = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMeasureUnit() {
    return measureUnit;
  }
  public void setMeasureUnit(String measureUnit) {
    this.measureUnit = measureUnit;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getWeighUnit() {
    return weighUnit;
  }
  public void setWeighUnit(String weighUnit) {
    this.weighUnit = weighUnit;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getPackageDepth() {
    return packageDepth;
  }
  public void setPackageDepth(BigDecimal packageDepth) {
    this.packageDepth = packageDepth;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getPackageLength() {
    return packageLength;
  }
  public void setPackageLength(BigDecimal packageLength) {
    this.packageLength = packageLength;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getPackageWidth() {
    return packageWidth;
  }
  public void setPackageWidth(BigDecimal packageWidth) {
    this.packageWidth = packageWidth;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getWeightMajor() {
    return weightMajor;
  }
  public void setWeightMajor(BigDecimal weightMajor) {
    this.weightMajor = weightMajor;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getWeightMinor() {
    return weightMinor;
  }
  public void setWeightMinor(BigDecimal weightMinor) {
    this.weightMinor = weightMinor;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getShippingPackage() {
    return shippingPackage;
  }
  public void setShippingPackage(String shippingPackage) {
    this.shippingPackage = shippingPackage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductAddPackageDetails productAddPackageDetails = (ProductAddPackageDetails) o;
    return (this.measureUnit == null ? productAddPackageDetails.measureUnit == null : this.measureUnit.equals(productAddPackageDetails.measureUnit)) &&
        (this.weighUnit == null ? productAddPackageDetails.weighUnit == null : this.weighUnit.equals(productAddPackageDetails.weighUnit)) &&
        (this.packageDepth == null ? productAddPackageDetails.packageDepth == null : this.packageDepth.equals(productAddPackageDetails.packageDepth)) &&
        (this.packageLength == null ? productAddPackageDetails.packageLength == null : this.packageLength.equals(productAddPackageDetails.packageLength)) &&
        (this.packageWidth == null ? productAddPackageDetails.packageWidth == null : this.packageWidth.equals(productAddPackageDetails.packageWidth)) &&
        (this.weightMajor == null ? productAddPackageDetails.weightMajor == null : this.weightMajor.equals(productAddPackageDetails.weightMajor)) &&
        (this.weightMinor == null ? productAddPackageDetails.weightMinor == null : this.weightMinor.equals(productAddPackageDetails.weightMinor)) &&
        (this.shippingPackage == null ? productAddPackageDetails.shippingPackage == null : this.shippingPackage.equals(productAddPackageDetails.shippingPackage));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.measureUnit == null ? 0: this.measureUnit.hashCode());
    result = 31 * result + (this.weighUnit == null ? 0: this.weighUnit.hashCode());
    result = 31 * result + (this.packageDepth == null ? 0: this.packageDepth.hashCode());
    result = 31 * result + (this.packageLength == null ? 0: this.packageLength.hashCode());
    result = 31 * result + (this.packageWidth == null ? 0: this.packageWidth.hashCode());
    result = 31 * result + (this.weightMajor == null ? 0: this.weightMajor.hashCode());
    result = 31 * result + (this.weightMinor == null ? 0: this.weightMinor.hashCode());
    result = 31 * result + (this.shippingPackage == null ? 0: this.shippingPackage.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductAddPackageDetails {\n");
    
    sb.append("  measureUnit: ").append(measureUnit).append("\n");
    sb.append("  weighUnit: ").append(weighUnit).append("\n");
    sb.append("  packageDepth: ").append(packageDepth).append("\n");
    sb.append("  packageLength: ").append(packageLength).append("\n");
    sb.append("  packageWidth: ").append(packageWidth).append("\n");
    sb.append("  weightMajor: ").append(weightMajor).append("\n");
    sb.append("  weightMinor: ").append(weightMinor).append("\n");
    sb.append("  shippingPackage: ").append(shippingPackage).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
