/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.math.BigDecimal;
import java.net.URI;
import java.util.*;
import org.openapitools.client.model.ProductAddBestOffer;
import org.openapitools.client.model.ProductAddCertificationsInner;
import org.openapitools.client.model.ProductAddFilesInner;
import org.openapitools.client.model.ProductAddGroupPricesInner;
import org.openapitools.client.model.ProductAddLogisticInfoInner;
import org.openapitools.client.model.ProductAddManufacturerInfo;
import org.openapitools.client.model.ProductAddPackageDetails;
import org.openapitools.client.model.ProductAddPersonalizationDetails;
import org.openapitools.client.model.ProductAddSalesTax;
import org.openapitools.client.model.ProductAddSellerProfiles;
import org.openapitools.client.model.ProductAddShippingDetailsInner;
import org.openapitools.client.model.ProductAddSizeChart;
import org.openapitools.client.model.ProductAddSpecificsInner;
import org.openapitools.client.model.ProductAddTierPricesInner;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ProductAdd {
  
  @SerializedName("name")
  private String name = null;
  @SerializedName("model")
  private String model = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("price")
  private BigDecimal price = null;
  @SerializedName("sku")
  private String sku = null;
  @SerializedName("short_description")
  private String shortDescription = null;
  @SerializedName("type")
  private String type = simple;
  @SerializedName("status")
  private String status = null;
  @SerializedName("visible")
  private String visible = null;
  @SerializedName("category_id")
  private String categoryId = null;
  @SerializedName("categories_ids")
  private String categoriesIds = null;
  @SerializedName("product_class")
  private String productClass = null;
  @SerializedName("product_type")
  private String productType = null;
  @SerializedName("is_virtual")
  private Boolean isVirtual = false;
  @SerializedName("downloadable")
  private Boolean downloadable = false;
  @SerializedName("is_supply")
  private Boolean isSupply = true;
  @SerializedName("available_for_view")
  private Boolean availableForView = true;
  @SerializedName("available_for_sale")
  private Boolean availableForSale = true;
  @SerializedName("store_id")
  private String storeId = null;
  @SerializedName("stores_ids")
  private String storesIds = null;
  @SerializedName("lang_id")
  private String langId = null;
  @SerializedName("old_price")
  private BigDecimal oldPrice = null;
  @SerializedName("special_price")
  private BigDecimal specialPrice = null;
  @SerializedName("wholesale_price")
  private BigDecimal wholesalePrice = null;
  @SerializedName("cost_price")
  private BigDecimal costPrice = null;
  @SerializedName("fixed_cost_shipping_price")
  private BigDecimal fixedCostShippingPrice = null;
  @SerializedName("tier_prices")
  private List<ProductAddTierPricesInner> tierPrices = null;
  @SerializedName("group_prices")
  private List<ProductAddGroupPricesInner> groupPrices = null;
  @SerializedName("buyitnow_price")
  private BigDecimal buyitnowPrice = null;
  @SerializedName("reserve_price")
  private BigDecimal reservePrice = null;
  @SerializedName("quantity")
  private BigDecimal quantity = 0;
  @SerializedName("in_stock")
  private Boolean inStock = null;
  @SerializedName("manage_stock")
  private Boolean manageStock = null;
  @SerializedName("warehouse_id")
  private String warehouseId = null;
  @SerializedName("backorder_status")
  private String backorderStatus = null;
  @SerializedName("min_order_quantity")
  private BigDecimal minOrderQuantity = null;
  @SerializedName("max_order_quantity")
  private BigDecimal maxOrderQuantity = null;
  @SerializedName("weight")
  private BigDecimal weight = 0;
  @SerializedName("weight_unit")
  private String weightUnit = null;
  @SerializedName("width")
  private BigDecimal width = null;
  @SerializedName("height")
  private BigDecimal height = null;
  @SerializedName("length")
  private BigDecimal length = null;
  @SerializedName("dimensions_unit")
  private String dimensionsUnit = null;
  @SerializedName("barcode")
  private String barcode = null;
  @SerializedName("upc")
  private String upc = null;
  @SerializedName("ean")
  private String ean = null;
  @SerializedName("isbn")
  private String isbn = null;
  @SerializedName("gtin")
  private String gtin = null;
  @SerializedName("mpn")
  private String mpn = null;
  @SerializedName("asin")
  private String asin = null;
  @SerializedName("product_reference")
  private String productReference = null;
  @SerializedName("harmonized_system_code")
  private String harmonizedSystemCode = null;
  @SerializedName("country_of_origin")
  private String countryOfOrigin = null;
  @SerializedName("manufacturer")
  private String manufacturer = null;
  @SerializedName("manufacturer_id")
  private String manufacturerId = null;
  @SerializedName("manufacturer_info")
  private ProductAddManufacturerInfo manufacturerInfo = null;
  @SerializedName("brand_name")
  private String brandName = null;
  @SerializedName("image_url")
  private String imageUrl = null;
  @SerializedName("image_name")
  private String imageName = null;
  @SerializedName("additional_image_urls")
  private List<URI> additionalImageUrls = null;
  @SerializedName("files")
  private List<ProductAddFilesInner> files = null;
  @SerializedName("size_chart")
  private ProductAddSizeChart sizeChart = null;
  @SerializedName("related_products_ids")
  private String relatedProductsIds = null;
  @SerializedName("up_sell_products_ids")
  private String upSellProductsIds = null;
  @SerializedName("cross_sell_products_ids")
  private String crossSellProductsIds = null;
  @SerializedName("attribute_set_name")
  private String attributeSetName = Default;
  @SerializedName("attribute_name")
  private String attributeName = null;
  @SerializedName("search_keywords")
  private String searchKeywords = null;
  @SerializedName("tags")
  private String tags = null;
  @SerializedName("materials")
  private List<String> materials = null;
  @SerializedName("certifications")
  private List<ProductAddCertificationsInner> certifications = null;
  @SerializedName("specifics")
  private List<ProductAddSpecificsInner> specifics = null;
  @SerializedName("avail_from")
  private String availFrom = null;
  @SerializedName("sprice_create")
  private String spriceCreate = null;
  @SerializedName("sprice_modified")
  private String spriceModified = null;
  @SerializedName("sprice_expire")
  private String spriceExpire = null;
  @SerializedName("created_at")
  private String createdAt = null;
  @SerializedName("auto_renew")
  private Boolean autoRenew = false;
  @SerializedName("when_made")
  private String whenMade = made_to_order;
  @SerializedName("meta_title")
  private String metaTitle = null;
  @SerializedName("meta_keywords")
  private String metaKeywords = null;
  @SerializedName("meta_description")
  private String metaDescription = null;
  @SerializedName("url")
  private String url = null;
  @SerializedName("seo_url")
  private String seoUrl = null;
  @SerializedName("tax_class_id")
  private String taxClassId = null;
  @SerializedName("taxable")
  private Boolean taxable = true;
  @SerializedName("sales_tax")
  private ProductAddSalesTax salesTax = null;
  @SerializedName("condition")
  private String condition = null;
  @SerializedName("condition_description")
  private String conditionDescription = null;
  @SerializedName("allow_display_condition")
  private Boolean allowDisplayCondition = null;
  @SerializedName("payment_methods")
  private List<String> paymentMethods = null;
  @SerializedName("paypal_email")
  private String paypalEmail = null;
  @SerializedName("shipping_template_id")
  private Integer shippingTemplateId = 0;
  @SerializedName("shipping_details")
  private List<ProductAddShippingDetailsInner> shippingDetails = null;
  @SerializedName("is_free_shipping")
  private Boolean isFreeShipping = null;
  @SerializedName("delivery_code")
  private String deliveryCode = null;
  @SerializedName("delivery_type")
  private String deliveryType = null;
  @SerializedName("delivery_time")
  private Integer deliveryTime = null;
  @SerializedName("delivery_option_ids")
  private String deliveryOptionIds = null;
  @SerializedName("package_details")
  private ProductAddPackageDetails packageDetails = null;
  @SerializedName("logistic_info")
  private List<ProductAddLogisticInfoInner> logisticInfo = null;
  @SerializedName("listing_duration")
  private String listingDuration = null;
  @SerializedName("listing_type")
  private String listingType = FixedPrice;
  @SerializedName("return_accepted")
  private Boolean returnAccepted = null;
  @SerializedName("seller_profiles")
  private ProductAddSellerProfiles sellerProfiles = null;
  @SerializedName("auction_confidentiality_level")
  private String auctionConfidentialityLevel = null;
  @SerializedName("best_offer")
  private ProductAddBestOffer bestOffer = null;
  @SerializedName("production_partner_ids")
  private String productionPartnerIds = null;
  @SerializedName("marketplace_item_properties")
  private String marketplaceItemProperties = null;
  @SerializedName("clear_cache")
  private Boolean clearCache = true;
  @SerializedName("viewed_count")
  private Integer viewedCount = 0;
  @SerializedName("ordered_count")
  private Integer orderedCount = 0;
  @SerializedName("shop_section_id")
  private Integer shopSectionId = null;
  @SerializedName("return_policy_id")
  private Integer returnPolicyId = null;
  @SerializedName("personalization_details")
  private ProductAddPersonalizationDetails personalizationDetails = null;

  /**
   * Defines product's name that has to be added
   **/
  @ApiModelProperty(required = true, value = "Defines product's name that has to be added")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Defines product's model that has to be added
   **/
  @ApiModelProperty(required = true, value = "Defines product's model that has to be added")
  public String getModel() {
    return model;
  }
  public void setModel(String model) {
    this.model = model;
  }

  /**
   * Defines product's description that has to be added
   **/
  @ApiModelProperty(required = true, value = "Defines product's description that has to be added")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * Defines product's price that has to be added
   **/
  @ApiModelProperty(required = true, value = "Defines product's price that has to be added")
  public BigDecimal getPrice() {
    return price;
  }
  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  /**
   * Defines product's sku that has to be added
   **/
  @ApiModelProperty(value = "Defines product's sku that has to be added")
  public String getSku() {
    return sku;
  }
  public void setSku(String sku) {
    this.sku = sku;
  }

  /**
   * Defines short description
   **/
  @ApiModelProperty(value = "Defines short description")
  public String getShortDescription() {
    return shortDescription;
  }
  public void setShortDescription(String shortDescription) {
    this.shortDescription = shortDescription;
  }

  /**
   * Defines product's type
   **/
  @ApiModelProperty(value = "Defines product's type")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   * Defines product's status
   **/
  @ApiModelProperty(value = "Defines product's status")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   * Set visibility status
   **/
  @ApiModelProperty(value = "Set visibility status")
  public String getVisible() {
    return visible;
  }
  public void setVisible(String visible) {
    this.visible = visible;
  }

  /**
   * Defines product add that is specified by category id
   **/
  @ApiModelProperty(value = "Defines product add that is specified by category id")
  public String getCategoryId() {
    return categoryId;
  }
  public void setCategoryId(String categoryId) {
    this.categoryId = categoryId;
  }

  /**
   * Defines product add that is specified by comma-separated categories id
   **/
  @ApiModelProperty(value = "Defines product add that is specified by comma-separated categories id")
  public String getCategoriesIds() {
    return categoriesIds;
  }
  public void setCategoriesIds(String categoriesIds) {
    this.categoriesIds = categoriesIds;
  }

  /**
   * A categorization for the product
   **/
  @ApiModelProperty(value = "A categorization for the product")
  public String getProductClass() {
    return productClass;
  }
  public void setProductClass(String productClass) {
    this.productClass = productClass;
  }

  /**
   * A categorization for the product
   **/
  @ApiModelProperty(value = "A categorization for the product")
  public String getProductType() {
    return productType;
  }
  public void setProductType(String productType) {
    this.productType = productType;
  }

  /**
   * Defines whether the product is virtual
   **/
  @ApiModelProperty(value = "Defines whether the product is virtual")
  public Boolean getIsVirtual() {
    return isVirtual;
  }
  public void setIsVirtual(Boolean isVirtual) {
    this.isVirtual = isVirtual;
  }

  /**
   * Defines whether the product is downloadable
   **/
  @ApiModelProperty(value = "Defines whether the product is downloadable")
  public Boolean getDownloadable() {
    return downloadable;
  }
  public void setDownloadable(Boolean downloadable) {
    this.downloadable = downloadable;
  }

  /**
   * If true, it indicates the product as a supply, otherwise it indicates that it is a finished product.
   **/
  @ApiModelProperty(value = "If true, it indicates the product as a supply, otherwise it indicates that it is a finished product.")
  public Boolean getIsSupply() {
    return isSupply;
  }
  public void setIsSupply(Boolean isSupply) {
    this.isSupply = isSupply;
  }

  /**
   * Specifies the set of visible/invisible products for users
   **/
  @ApiModelProperty(value = "Specifies the set of visible/invisible products for users")
  public Boolean getAvailableForView() {
    return availableForView;
  }
  public void setAvailableForView(Boolean availableForView) {
    this.availableForView = availableForView;
  }

  /**
   * Specifies the set of visible/invisible products for sale
   **/
  @ApiModelProperty(value = "Specifies the set of visible/invisible products for sale")
  public Boolean getAvailableForSale() {
    return availableForSale;
  }
  public void setAvailableForSale(Boolean availableForSale) {
    this.availableForSale = availableForSale;
  }

  /**
   * Store Id
   **/
  @ApiModelProperty(value = "Store Id")
  public String getStoreId() {
    return storeId;
  }
  public void setStoreId(String storeId) {
    this.storeId = storeId;
  }

  /**
   * Assign product to the stores that is specified by comma-separated stores' id
   **/
  @ApiModelProperty(value = "Assign product to the stores that is specified by comma-separated stores' id")
  public String getStoresIds() {
    return storesIds;
  }
  public void setStoresIds(String storesIds) {
    this.storesIds = storesIds;
  }

  /**
   * Language id
   **/
  @ApiModelProperty(value = "Language id")
  public String getLangId() {
    return langId;
  }
  public void setLangId(String langId) {
    this.langId = langId;
  }

  /**
   * Defines product's old price
   **/
  @ApiModelProperty(value = "Defines product's old price")
  public BigDecimal getOldPrice() {
    return oldPrice;
  }
  public void setOldPrice(BigDecimal oldPrice) {
    this.oldPrice = oldPrice;
  }

  /**
   * Defines product's model that has to be added
   **/
  @ApiModelProperty(value = "Defines product's model that has to be added")
  public BigDecimal getSpecialPrice() {
    return specialPrice;
  }
  public void setSpecialPrice(BigDecimal specialPrice) {
    this.specialPrice = specialPrice;
  }

  /**
   * Defines product's sale price
   **/
  @ApiModelProperty(value = "Defines product's sale price")
  public BigDecimal getWholesalePrice() {
    return wholesalePrice;
  }
  public void setWholesalePrice(BigDecimal wholesalePrice) {
    this.wholesalePrice = wholesalePrice;
  }

  /**
   * Defines new product's cost price
   **/
  @ApiModelProperty(value = "Defines new product's cost price")
  public BigDecimal getCostPrice() {
    return costPrice;
  }
  public void setCostPrice(BigDecimal costPrice) {
    this.costPrice = costPrice;
  }

  /**
   * Specifies product's fixed cost shipping price
   **/
  @ApiModelProperty(value = "Specifies product's fixed cost shipping price")
  public BigDecimal getFixedCostShippingPrice() {
    return fixedCostShippingPrice;
  }
  public void setFixedCostShippingPrice(BigDecimal fixedCostShippingPrice) {
    this.fixedCostShippingPrice = fixedCostShippingPrice;
  }

  /**
   * Defines product's tier prices
   **/
  @ApiModelProperty(value = "Defines product's tier prices")
  public List<ProductAddTierPricesInner> getTierPrices() {
    return tierPrices;
  }
  public void setTierPrices(List<ProductAddTierPricesInner> tierPrices) {
    this.tierPrices = tierPrices;
  }

  /**
   * Defines product's group prices
   **/
  @ApiModelProperty(value = "Defines product's group prices")
  public List<ProductAddGroupPricesInner> getGroupPrices() {
    return groupPrices;
  }
  public void setGroupPrices(List<ProductAddGroupPricesInner> groupPrices) {
    this.groupPrices = groupPrices;
  }

  /**
   * Defines buy it now value
   **/
  @ApiModelProperty(value = "Defines buy it now value")
  public BigDecimal getBuyitnowPrice() {
    return buyitnowPrice;
  }
  public void setBuyitnowPrice(BigDecimal buyitnowPrice) {
    this.buyitnowPrice = buyitnowPrice;
  }

  /**
   * Defines reserve price value
   **/
  @ApiModelProperty(value = "Defines reserve price value")
  public BigDecimal getReservePrice() {
    return reservePrice;
  }
  public void setReservePrice(BigDecimal reservePrice) {
    this.reservePrice = reservePrice;
  }

  /**
   * Defines product's quantity that has to be added
   **/
  @ApiModelProperty(value = "Defines product's quantity that has to be added")
  public BigDecimal getQuantity() {
    return quantity;
  }
  public void setQuantity(BigDecimal quantity) {
    this.quantity = quantity;
  }

  /**
   * Set stock status
   **/
  @ApiModelProperty(value = "Set stock status")
  public Boolean getInStock() {
    return inStock;
  }
  public void setInStock(Boolean inStock) {
    this.inStock = inStock;
  }

  /**
   * Defines inventory tracking for product
   **/
  @ApiModelProperty(value = "Defines inventory tracking for product")
  public Boolean getManageStock() {
    return manageStock;
  }
  public void setManageStock(Boolean manageStock) {
    this.manageStock = manageStock;
  }

  /**
   * This parameter is used for selecting a warehouse where you need to set/modify a product quantity.
   **/
  @ApiModelProperty(value = "This parameter is used for selecting a warehouse where you need to set/modify a product quantity.")
  public String getWarehouseId() {
    return warehouseId;
  }
  public void setWarehouseId(String warehouseId) {
    this.warehouseId = warehouseId;
  }

  /**
   * Set backorder status
   **/
  @ApiModelProperty(value = "Set backorder status")
  public String getBackorderStatus() {
    return backorderStatus;
  }
  public void setBackorderStatus(String backorderStatus) {
    this.backorderStatus = backorderStatus;
  }

  /**
   * The minimum quantity an order must contain, to be eligible to purchase this product.
   **/
  @ApiModelProperty(value = "The minimum quantity an order must contain, to be eligible to purchase this product.")
  public BigDecimal getMinOrderQuantity() {
    return minOrderQuantity;
  }
  public void setMinOrderQuantity(BigDecimal minOrderQuantity) {
    this.minOrderQuantity = minOrderQuantity;
  }

  /**
   * The maximum quantity an order can contain when purchasing the product.
   **/
  @ApiModelProperty(value = "The maximum quantity an order can contain when purchasing the product.")
  public BigDecimal getMaxOrderQuantity() {
    return maxOrderQuantity;
  }
  public void setMaxOrderQuantity(BigDecimal maxOrderQuantity) {
    this.maxOrderQuantity = maxOrderQuantity;
  }

  /**
   * Weight
   **/
  @ApiModelProperty(value = "Weight")
  public BigDecimal getWeight() {
    return weight;
  }
  public void setWeight(BigDecimal weight) {
    this.weight = weight;
  }

  /**
   * Weight Unit
   **/
  @ApiModelProperty(value = "Weight Unit")
  public String getWeightUnit() {
    return weightUnit;
  }
  public void setWeightUnit(String weightUnit) {
    this.weightUnit = weightUnit;
  }

  /**
   * Defines product's width
   **/
  @ApiModelProperty(value = "Defines product's width")
  public BigDecimal getWidth() {
    return width;
  }
  public void setWidth(BigDecimal width) {
    this.width = width;
  }

  /**
   * Defines product's height
   **/
  @ApiModelProperty(value = "Defines product's height")
  public BigDecimal getHeight() {
    return height;
  }
  public void setHeight(BigDecimal height) {
    this.height = height;
  }

  /**
   * Defines product's length
   **/
  @ApiModelProperty(value = "Defines product's length")
  public BigDecimal getLength() {
    return length;
  }
  public void setLength(BigDecimal length) {
    this.length = length;
  }

  /**
   * Weight Unit
   **/
  @ApiModelProperty(value = "Weight Unit")
  public String getDimensionsUnit() {
    return dimensionsUnit;
  }
  public void setDimensionsUnit(String dimensionsUnit) {
    this.dimensionsUnit = dimensionsUnit;
  }

  /**
   * A barcode is a unique code composed of numbers used as a product identifier.
   **/
  @ApiModelProperty(value = "A barcode is a unique code composed of numbers used as a product identifier.")
  public String getBarcode() {
    return barcode;
  }
  public void setBarcode(String barcode) {
    this.barcode = barcode;
  }

  /**
   * Universal Product Code. A UPC (UPC-A) is a commonly used identifer for many different products.
   **/
  @ApiModelProperty(value = "Universal Product Code. A UPC (UPC-A) is a commonly used identifer for many different products.")
  public String getUpc() {
    return upc;
  }
  public void setUpc(String upc) {
    this.upc = upc;
  }

  /**
   * European Article Number. An EAN is a unique 8 or 13-digit identifier that many industries (such as book publishers) use to identify products.
   **/
  @ApiModelProperty(value = "European Article Number. An EAN is a unique 8 or 13-digit identifier that many industries (such as book publishers) use to identify products.")
  public String getEan() {
    return ean;
  }
  public void setEan(String ean) {
    this.ean = ean;
  }

  /**
   * International Standard Book Number. An ISBN is a unique identifier for books.
   **/
  @ApiModelProperty(value = "International Standard Book Number. An ISBN is a unique identifier for books.")
  public String getIsbn() {
    return isbn;
  }
  public void setIsbn(String isbn) {
    this.isbn = isbn;
  }

  /**
   * Global Trade Item Number. An GTIN is an identifier for trade items.
   **/
  @ApiModelProperty(value = "Global Trade Item Number. An GTIN is an identifier for trade items.")
  public String getGtin() {
    return gtin;
  }
  public void setGtin(String gtin) {
    this.gtin = gtin;
  }

  /**
   * Manufacturer Part Number. A MPN is an identifier of a particular part design or material used.
   **/
  @ApiModelProperty(value = "Manufacturer Part Number. A MPN is an identifier of a particular part design or material used.")
  public String getMpn() {
    return mpn;
  }
  public void setMpn(String mpn) {
    this.mpn = mpn;
  }

  /**
   * Amazon Standard Identification Number.
   **/
  @ApiModelProperty(value = "Amazon Standard Identification Number.")
  public String getAsin() {
    return asin;
  }
  public void setAsin(String asin) {
    this.asin = asin;
  }

  /**
   * Groups all variations, that you want to combine into one product.
   **/
  @ApiModelProperty(value = "Groups all variations, that you want to combine into one product.")
  public String getProductReference() {
    return productReference;
  }
  public void setProductReference(String productReference) {
    this.productReference = productReference;
  }

  /**
   * Harmonized System Code. An HSC is a 6-digit identifier that allows participating countries to classify traded goods on a common basis for customs purposes
   **/
  @ApiModelProperty(value = "Harmonized System Code. An HSC is a 6-digit identifier that allows participating countries to classify traded goods on a common basis for customs purposes")
  public String getHarmonizedSystemCode() {
    return harmonizedSystemCode;
  }
  public void setHarmonizedSystemCode(String harmonizedSystemCode) {
    this.harmonizedSystemCode = harmonizedSystemCode;
  }

  /**
   * The country where the inventory item was made
   **/
  @ApiModelProperty(value = "The country where the inventory item was made")
  public String getCountryOfOrigin() {
    return countryOfOrigin;
  }
  public void setCountryOfOrigin(String countryOfOrigin) {
    this.countryOfOrigin = countryOfOrigin;
  }

  /**
   * Defines product's manufacturer
   **/
  @ApiModelProperty(value = "Defines product's manufacturer")
  public String getManufacturer() {
    return manufacturer;
  }
  public void setManufacturer(String manufacturer) {
    this.manufacturer = manufacturer;
  }

  /**
   * Defines product's manufacturer by manufacturer_id
   **/
  @ApiModelProperty(value = "Defines product's manufacturer by manufacturer_id")
  public String getManufacturerId() {
    return manufacturerId;
  }
  public void setManufacturerId(String manufacturerId) {
    this.manufacturerId = manufacturerId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ProductAddManufacturerInfo getManufacturerInfo() {
    return manufacturerInfo;
  }
  public void setManufacturerInfo(ProductAddManufacturerInfo manufacturerInfo) {
    this.manufacturerInfo = manufacturerInfo;
  }

  /**
   * Defines product brand name
   **/
  @ApiModelProperty(value = "Defines product brand name")
  public String getBrandName() {
    return brandName;
  }
  public void setBrandName(String brandName) {
    this.brandName = brandName;
  }

  /**
   * Image Url
   **/
  @ApiModelProperty(value = "Image Url")
  public String getImageUrl() {
    return imageUrl;
  }
  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }

  /**
   * Defines image's name
   **/
  @ApiModelProperty(value = "Defines image's name")
  public String getImageName() {
    return imageName;
  }
  public void setImageName(String imageName) {
    this.imageName = imageName;
  }

  /**
   * Image Url
   **/
  @ApiModelProperty(value = "Image Url")
  public List<URI> getAdditionalImageUrls() {
    return additionalImageUrls;
  }
  public void setAdditionalImageUrls(List<URI> additionalImageUrls) {
    this.additionalImageUrls = additionalImageUrls;
  }

  /**
   * File Url
   **/
  @ApiModelProperty(value = "File Url")
  public List<ProductAddFilesInner> getFiles() {
    return files;
  }
  public void setFiles(List<ProductAddFilesInner> files) {
    this.files = files;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ProductAddSizeChart getSizeChart() {
    return sizeChart;
  }
  public void setSizeChart(ProductAddSizeChart sizeChart) {
    this.sizeChart = sizeChart;
  }

  /**
   * Defines product's related products ids that has to be added
   **/
  @ApiModelProperty(value = "Defines product's related products ids that has to be added")
  public String getRelatedProductsIds() {
    return relatedProductsIds;
  }
  public void setRelatedProductsIds(String relatedProductsIds) {
    this.relatedProductsIds = relatedProductsIds;
  }

  /**
   * Defines product's up-sell products ids that has to be added
   **/
  @ApiModelProperty(value = "Defines product's up-sell products ids that has to be added")
  public String getUpSellProductsIds() {
    return upSellProductsIds;
  }
  public void setUpSellProductsIds(String upSellProductsIds) {
    this.upSellProductsIds = upSellProductsIds;
  }

  /**
   * Defines product's cross-sell products ids that has to be added
   **/
  @ApiModelProperty(value = "Defines product's cross-sell products ids that has to be added")
  public String getCrossSellProductsIds() {
    return crossSellProductsIds;
  }
  public void setCrossSellProductsIds(String crossSellProductsIds) {
    this.crossSellProductsIds = crossSellProductsIds;
  }

  /**
   * Defines product’s attribute set name in Magento
   **/
  @ApiModelProperty(value = "Defines product’s attribute set name in Magento")
  public String getAttributeSetName() {
    return attributeSetName;
  }
  public void setAttributeSetName(String attributeSetName) {
    this.attributeSetName = attributeSetName;
  }

  /**
   * Defines product’s attribute name separated with a comma in Magento
   **/
  @ApiModelProperty(value = "Defines product’s attribute name separated with a comma in Magento")
  public String getAttributeName() {
    return attributeName;
  }
  public void setAttributeName(String attributeName) {
    this.attributeName = attributeName;
  }

  /**
   * Defines unique search keywords
   **/
  @ApiModelProperty(value = "Defines unique search keywords")
  public String getSearchKeywords() {
    return searchKeywords;
  }
  public void setSearchKeywords(String searchKeywords) {
    this.searchKeywords = searchKeywords;
  }

  /**
   * Product tags
   **/
  @ApiModelProperty(value = "Product tags")
  public String getTags() {
    return tags;
  }
  public void setTags(String tags) {
    this.tags = tags;
  }

  /**
   * A list of material strings for materials used in the product.
   **/
  @ApiModelProperty(value = "A list of material strings for materials used in the product.")
  public List<String> getMaterials() {
    return materials;
  }
  public void setMaterials(List<String> materials) {
    this.materials = materials;
  }

  /**
   * An array of product certifications. The list of possible certifications can be obtained using the \"<i>category.info</i>\" method (<i>additional_fields->rules->product_certifications</i>).
   **/
  @ApiModelProperty(value = "An array of product certifications. The list of possible certifications can be obtained using the \"<i>category.info</i>\" method (<i>additional_fields->rules->product_certifications</i>).")
  public List<ProductAddCertificationsInner> getCertifications() {
    return certifications;
  }
  public void setCertifications(List<ProductAddCertificationsInner> certifications) {
    this.certifications = certifications;
  }

  /**
   * An array of Item Specific Name/Value pairs used by the seller to provide descriptive details of an item in a structured manner.         The list of possible specifications can be obtained using the category.info method (additional_fields->product_specifics).         <b>The structure of the parameter is different for specific platforms.</b>
   **/
  @ApiModelProperty(value = "An array of Item Specific Name/Value pairs used by the seller to provide descriptive details of an item in a structured manner.         The list of possible specifications can be obtained using the category.info method (additional_fields->product_specifics).         <b>The structure of the parameter is different for specific platforms.</b>")
  public List<ProductAddSpecificsInner> getSpecifics() {
    return specifics;
  }
  public void setSpecifics(List<ProductAddSpecificsInner> specifics) {
    this.specifics = specifics;
  }

  /**
   * Allows to schedule a time in the future that the item becomes available. The value should be greater than the current date and time.
   **/
  @ApiModelProperty(value = "Allows to schedule a time in the future that the item becomes available. The value should be greater than the current date and time.")
  public String getAvailFrom() {
    return availFrom;
  }
  public void setAvailFrom(String availFrom) {
    this.availFrom = availFrom;
  }

  /**
   * Defines the date of special price creation
   **/
  @ApiModelProperty(value = "Defines the date of special price creation")
  public String getSpriceCreate() {
    return spriceCreate;
  }
  public void setSpriceCreate(String spriceCreate) {
    this.spriceCreate = spriceCreate;
  }

  /**
   * Defines the date of special price modification
   **/
  @ApiModelProperty(value = "Defines the date of special price modification")
  public String getSpriceModified() {
    return spriceModified;
  }
  public void setSpriceModified(String spriceModified) {
    this.spriceModified = spriceModified;
  }

  /**
   * Defines the term of special price offer duration
   **/
  @ApiModelProperty(value = "Defines the term of special price offer duration")
  public String getSpriceExpire() {
    return spriceExpire;
  }
  public void setSpriceExpire(String spriceExpire) {
    this.spriceExpire = spriceExpire;
  }

  /**
   * Defines the date of entity creation
   **/
  @ApiModelProperty(value = "Defines the date of entity creation")
  public String getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  /**
   * When true, automatically renews a listing upon its expiration.
   **/
  @ApiModelProperty(value = "When true, automatically renews a listing upon its expiration.")
  public Boolean getAutoRenew() {
    return autoRenew;
  }
  public void setAutoRenew(Boolean autoRenew) {
    this.autoRenew = autoRenew;
  }

  /**
   * An enumerated string for the era in which the maker made the product.
   **/
  @ApiModelProperty(value = "An enumerated string for the era in which the maker made the product.")
  public String getWhenMade() {
    return whenMade;
  }
  public void setWhenMade(String whenMade) {
    this.whenMade = whenMade;
  }

  /**
   * Defines unique meta title for each entity
   **/
  @ApiModelProperty(value = "Defines unique meta title for each entity")
  public String getMetaTitle() {
    return metaTitle;
  }
  public void setMetaTitle(String metaTitle) {
    this.metaTitle = metaTitle;
  }

  /**
   * Defines unique meta keywords for each entity
   **/
  @ApiModelProperty(value = "Defines unique meta keywords for each entity")
  public String getMetaKeywords() {
    return metaKeywords;
  }
  public void setMetaKeywords(String metaKeywords) {
    this.metaKeywords = metaKeywords;
  }

  /**
   * Defines unique meta description of a entity
   **/
  @ApiModelProperty(value = "Defines unique meta description of a entity")
  public String getMetaDescription() {
    return metaDescription;
  }
  public void setMetaDescription(String metaDescription) {
    this.metaDescription = metaDescription;
  }

  /**
   * Defines unique product's URL
   **/
  @ApiModelProperty(value = "Defines unique product's URL")
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   * Defines unique URL for SEO
   **/
  @ApiModelProperty(value = "Defines unique URL for SEO")
  public String getSeoUrl() {
    return seoUrl;
  }
  public void setSeoUrl(String seoUrl) {
    this.seoUrl = seoUrl;
  }

  /**
   * Defines tax classes where entity has to be added
   **/
  @ApiModelProperty(value = "Defines tax classes where entity has to be added")
  public String getTaxClassId() {
    return taxClassId;
  }
  public void setTaxClassId(String taxClassId) {
    this.taxClassId = taxClassId;
  }

  /**
   * Specifies whether a tax is charged
   **/
  @ApiModelProperty(value = "Specifies whether a tax is charged")
  public Boolean getTaxable() {
    return taxable;
  }
  public void setTaxable(Boolean taxable) {
    this.taxable = taxable;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ProductAddSalesTax getSalesTax() {
    return salesTax;
  }
  public void setSalesTax(ProductAddSalesTax salesTax) {
    this.salesTax = salesTax;
  }

  /**
   * The human-readable label for the condition (e.g., \"New\").
   **/
  @ApiModelProperty(value = "The human-readable label for the condition (e.g., \"New\").")
  public String getCondition() {
    return condition;
  }
  public void setCondition(String condition) {
    this.condition = condition;
  }

  /**
   * Detailed description of the product condition.
   **/
  @ApiModelProperty(value = "Detailed description of the product condition.")
  public String getConditionDescription() {
    return conditionDescription;
  }
  public void setConditionDescription(String conditionDescription) {
    this.conditionDescription = conditionDescription;
  }

  /**
   * Flag used to determine whether the product condition is shown to the customer on the product page.
   **/
  @ApiModelProperty(value = "Flag used to determine whether the product condition is shown to the customer on the product page.")
  public Boolean getAllowDisplayCondition() {
    return allowDisplayCondition;
  }
  public void setAllowDisplayCondition(Boolean allowDisplayCondition) {
    this.allowDisplayCondition = allowDisplayCondition;
  }

  /**
   * Identifies the payment method (such as PayPal) that the seller will accept when the buyer pays for the item. Look at cart.info method response for allowed values.<hr><div style=\"font-style:normal\">Param structure:<div style=\"margin-left: 2%;\"><code style=\"padding:0; background-color:#ffffff;font-size:85%;font-family:monospace;\">payment_methods[0] = string</br>payment_methods[1] = string</br></code></div></div>
   **/
  @ApiModelProperty(value = "Identifies the payment method (such as PayPal) that the seller will accept when the buyer pays for the item. Look at cart.info method response for allowed values.<hr><div style=\"font-style:normal\">Param structure:<div style=\"margin-left: 2%;\"><code style=\"padding:0; background-color:#ffffff;font-size:85%;font-family:monospace;\">payment_methods[0] = string</br>payment_methods[1] = string</br></code></div></div>")
  public List<String> getPaymentMethods() {
    return paymentMethods;
  }
  public void setPaymentMethods(List<String> paymentMethods) {
    this.paymentMethods = paymentMethods;
  }

  /**
   * Valid PayPal email address for the PayPal account that the seller will use if they offer PayPal as a payment method for the listing.
   **/
  @ApiModelProperty(value = "Valid PayPal email address for the PayPal account that the seller will use if they offer PayPal as a payment method for the listing.")
  public String getPaypalEmail() {
    return paypalEmail;
  }
  public void setPaypalEmail(String paypalEmail) {
    this.paypalEmail = paypalEmail;
  }

  /**
   * The numeric ID of the shipping template associated with the products in Etsy. You can find possible values in the \"cart.info\" API method response, in the field shipping_zones[]->id.
   **/
  @ApiModelProperty(value = "The numeric ID of the shipping template associated with the products in Etsy. You can find possible values in the \"cart.info\" API method response, in the field shipping_zones[]->id.")
  public Integer getShippingTemplateId() {
    return shippingTemplateId;
  }
  public void setShippingTemplateId(Integer shippingTemplateId) {
    this.shippingTemplateId = shippingTemplateId;
  }

  /**
   * The shipping details, including flat and calculated shipping costs and shipping insurance costs. Look at cart.info method response for allowed values.<hr><div style=\"font-style:normal\">Param structure:<div style=\"margin-left: 2%;\"><code style=\"padding:0; background-color:#ffffff;font-size:85%;font-family:monospace;\">shipping_details[0][<b>shipping_type</b>] = string </br>shipping_details[0][<b>shipping_service</b>] = string</br>shipping_details[0][<b>shipping_cost</b>] = decimal</br>shipping_details[1][<b>shipping_type</b>] = string </br>shipping_details[1][<b>shipping_service</b>] = string</br>shipping_details[1][<b>shipping_cost</b>] = decimal</br></code></div></div>
   **/
  @ApiModelProperty(value = "The shipping details, including flat and calculated shipping costs and shipping insurance costs. Look at cart.info method response for allowed values.<hr><div style=\"font-style:normal\">Param structure:<div style=\"margin-left: 2%;\"><code style=\"padding:0; background-color:#ffffff;font-size:85%;font-family:monospace;\">shipping_details[0][<b>shipping_type</b>] = string </br>shipping_details[0][<b>shipping_service</b>] = string</br>shipping_details[0][<b>shipping_cost</b>] = decimal</br>shipping_details[1][<b>shipping_type</b>] = string </br>shipping_details[1][<b>shipping_service</b>] = string</br>shipping_details[1][<b>shipping_cost</b>] = decimal</br></code></div></div>")
  public List<ProductAddShippingDetailsInner> getShippingDetails() {
    return shippingDetails;
  }
  public void setShippingDetails(List<ProductAddShippingDetailsInner> shippingDetails) {
    this.shippingDetails = shippingDetails;
  }

  /**
   * Specifies product's free shipping flag that has to be added
   **/
  @ApiModelProperty(value = "Specifies product's free shipping flag that has to be added")
  public Boolean getIsFreeShipping() {
    return isFreeShipping;
  }
  public void setIsFreeShipping(Boolean isFreeShipping) {
    this.isFreeShipping = isFreeShipping;
  }

  /**
   * The delivery promise that applies to offer
   **/
  @ApiModelProperty(value = "The delivery promise that applies to offer")
  public String getDeliveryCode() {
    return deliveryCode;
  }
  public void setDeliveryCode(String deliveryCode) {
    this.deliveryCode = deliveryCode;
  }

  /**
   * Defines the type of the delivery.
   **/
  @ApiModelProperty(value = "Defines the type of the delivery.")
  public String getDeliveryType() {
    return deliveryType;
  }
  public void setDeliveryType(String deliveryType) {
    this.deliveryType = deliveryType;
  }

  /**
   * Defines delivery time in days.
   **/
  @ApiModelProperty(value = "Defines delivery time in days.")
  public Integer getDeliveryTime() {
    return deliveryTime;
  }
  public void setDeliveryTime(Integer deliveryTime) {
    this.deliveryTime = deliveryTime;
  }

  /**
   * Defines delivery options for product by ids.
   **/
  @ApiModelProperty(value = "Defines delivery options for product by ids.")
  public String getDeliveryOptionIds() {
    return deliveryOptionIds;
  }
  public void setDeliveryOptionIds(String deliveryOptionIds) {
    this.deliveryOptionIds = deliveryOptionIds;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ProductAddPackageDetails getPackageDetails() {
    return packageDetails;
  }
  public void setPackageDetails(ProductAddPackageDetails packageDetails) {
    this.packageDetails = packageDetails;
  }

  /**
   * Defines product's logistic channel settings
   **/
  @ApiModelProperty(value = "Defines product's logistic channel settings")
  public List<ProductAddLogisticInfoInner> getLogisticInfo() {
    return logisticInfo;
  }
  public void setLogisticInfo(List<ProductAddLogisticInfoInner> logisticInfo) {
    this.logisticInfo = logisticInfo;
  }

  /**
   * Describes the number of days the seller wants the listing to be active. Look at cart.info method response for allowed values.
   **/
  @ApiModelProperty(value = "Describes the number of days the seller wants the listing to be active. Look at cart.info method response for allowed values.")
  public String getListingDuration() {
    return listingDuration;
  }
  public void setListingDuration(String listingDuration) {
    this.listingDuration = listingDuration;
  }

  /**
   * Indicates the selling format of the marketplace listing.
   **/
  @ApiModelProperty(value = "Indicates the selling format of the marketplace listing.")
  public String getListingType() {
    return listingType;
  }
  public void setListingType(String listingType) {
    this.listingType = listingType;
  }

  /**
   * Indicates whether the seller allows the buyer to return the item.
   **/
  @ApiModelProperty(value = "Indicates whether the seller allows the buyer to return the item.")
  public Boolean getReturnAccepted() {
    return returnAccepted;
  }
  public void setReturnAccepted(Boolean returnAccepted) {
    this.returnAccepted = returnAccepted;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ProductAddSellerProfiles getSellerProfiles() {
    return sellerProfiles;
  }
  public void setSellerProfiles(ProductAddSellerProfiles sellerProfiles) {
    this.sellerProfiles = sellerProfiles;
  }

  /**
   * This allows buyers to remain anonymous when the bid or buy an item.
   **/
  @ApiModelProperty(value = "This allows buyers to remain anonymous when the bid or buy an item.")
  public String getAuctionConfidentialityLevel() {
    return auctionConfidentialityLevel;
  }
  public void setAuctionConfidentialityLevel(String auctionConfidentialityLevel) {
    this.auctionConfidentialityLevel = auctionConfidentialityLevel;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ProductAddBestOffer getBestOffer() {
    return bestOffer;
  }
  public void setBestOffer(ProductAddBestOffer bestOffer) {
    this.bestOffer = bestOffer;
  }

  /**
   * Defines product's production partner ids that has to be added
   **/
  @ApiModelProperty(value = "Defines product's production partner ids that has to be added")
  public String getProductionPartnerIds() {
    return productionPartnerIds;
  }
  public void setProductionPartnerIds(String productionPartnerIds) {
    this.productionPartnerIds = productionPartnerIds;
  }

  /**
   * String containing the JSON representation of the supplied data
   **/
  @ApiModelProperty(value = "String containing the JSON representation of the supplied data")
  public String getMarketplaceItemProperties() {
    return marketplaceItemProperties;
  }
  public void setMarketplaceItemProperties(String marketplaceItemProperties) {
    this.marketplaceItemProperties = marketplaceItemProperties;
  }

  /**
   * Is cache clear required
   **/
  @ApiModelProperty(value = "Is cache clear required")
  public Boolean getClearCache() {
    return clearCache;
  }
  public void setClearCache(Boolean clearCache) {
    this.clearCache = clearCache;
  }

  /**
   * Specifies the number of product's reviews
   **/
  @ApiModelProperty(value = "Specifies the number of product's reviews")
  public Integer getViewedCount() {
    return viewedCount;
  }
  public void setViewedCount(Integer viewedCount) {
    this.viewedCount = viewedCount;
  }

  /**
   * Defines how many times the product was ordered
   **/
  @ApiModelProperty(value = "Defines how many times the product was ordered")
  public Integer getOrderedCount() {
    return orderedCount;
  }
  public void setOrderedCount(Integer orderedCount) {
    this.orderedCount = orderedCount;
  }

  /**
   * Add Shop Section Id
   **/
  @ApiModelProperty(value = "Add Shop Section Id")
  public Integer getShopSectionId() {
    return shopSectionId;
  }
  public void setShopSectionId(Integer shopSectionId) {
    this.shopSectionId = shopSectionId;
  }

  /**
   * Add Return Policy Id
   **/
  @ApiModelProperty(value = "Add Return Policy Id")
  public Integer getReturnPolicyId() {
    return returnPolicyId;
  }
  public void setReturnPolicyId(Integer returnPolicyId) {
    this.returnPolicyId = returnPolicyId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ProductAddPersonalizationDetails getPersonalizationDetails() {
    return personalizationDetails;
  }
  public void setPersonalizationDetails(ProductAddPersonalizationDetails personalizationDetails) {
    this.personalizationDetails = personalizationDetails;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductAdd productAdd = (ProductAdd) o;
    return (this.name == null ? productAdd.name == null : this.name.equals(productAdd.name)) &&
        (this.model == null ? productAdd.model == null : this.model.equals(productAdd.model)) &&
        (this.description == null ? productAdd.description == null : this.description.equals(productAdd.description)) &&
        (this.price == null ? productAdd.price == null : this.price.equals(productAdd.price)) &&
        (this.sku == null ? productAdd.sku == null : this.sku.equals(productAdd.sku)) &&
        (this.shortDescription == null ? productAdd.shortDescription == null : this.shortDescription.equals(productAdd.shortDescription)) &&
        (this.type == null ? productAdd.type == null : this.type.equals(productAdd.type)) &&
        (this.status == null ? productAdd.status == null : this.status.equals(productAdd.status)) &&
        (this.visible == null ? productAdd.visible == null : this.visible.equals(productAdd.visible)) &&
        (this.categoryId == null ? productAdd.categoryId == null : this.categoryId.equals(productAdd.categoryId)) &&
        (this.categoriesIds == null ? productAdd.categoriesIds == null : this.categoriesIds.equals(productAdd.categoriesIds)) &&
        (this.productClass == null ? productAdd.productClass == null : this.productClass.equals(productAdd.productClass)) &&
        (this.productType == null ? productAdd.productType == null : this.productType.equals(productAdd.productType)) &&
        (this.isVirtual == null ? productAdd.isVirtual == null : this.isVirtual.equals(productAdd.isVirtual)) &&
        (this.downloadable == null ? productAdd.downloadable == null : this.downloadable.equals(productAdd.downloadable)) &&
        (this.isSupply == null ? productAdd.isSupply == null : this.isSupply.equals(productAdd.isSupply)) &&
        (this.availableForView == null ? productAdd.availableForView == null : this.availableForView.equals(productAdd.availableForView)) &&
        (this.availableForSale == null ? productAdd.availableForSale == null : this.availableForSale.equals(productAdd.availableForSale)) &&
        (this.storeId == null ? productAdd.storeId == null : this.storeId.equals(productAdd.storeId)) &&
        (this.storesIds == null ? productAdd.storesIds == null : this.storesIds.equals(productAdd.storesIds)) &&
        (this.langId == null ? productAdd.langId == null : this.langId.equals(productAdd.langId)) &&
        (this.oldPrice == null ? productAdd.oldPrice == null : this.oldPrice.equals(productAdd.oldPrice)) &&
        (this.specialPrice == null ? productAdd.specialPrice == null : this.specialPrice.equals(productAdd.specialPrice)) &&
        (this.wholesalePrice == null ? productAdd.wholesalePrice == null : this.wholesalePrice.equals(productAdd.wholesalePrice)) &&
        (this.costPrice == null ? productAdd.costPrice == null : this.costPrice.equals(productAdd.costPrice)) &&
        (this.fixedCostShippingPrice == null ? productAdd.fixedCostShippingPrice == null : this.fixedCostShippingPrice.equals(productAdd.fixedCostShippingPrice)) &&
        (this.tierPrices == null ? productAdd.tierPrices == null : this.tierPrices.equals(productAdd.tierPrices)) &&
        (this.groupPrices == null ? productAdd.groupPrices == null : this.groupPrices.equals(productAdd.groupPrices)) &&
        (this.buyitnowPrice == null ? productAdd.buyitnowPrice == null : this.buyitnowPrice.equals(productAdd.buyitnowPrice)) &&
        (this.reservePrice == null ? productAdd.reservePrice == null : this.reservePrice.equals(productAdd.reservePrice)) &&
        (this.quantity == null ? productAdd.quantity == null : this.quantity.equals(productAdd.quantity)) &&
        (this.inStock == null ? productAdd.inStock == null : this.inStock.equals(productAdd.inStock)) &&
        (this.manageStock == null ? productAdd.manageStock == null : this.manageStock.equals(productAdd.manageStock)) &&
        (this.warehouseId == null ? productAdd.warehouseId == null : this.warehouseId.equals(productAdd.warehouseId)) &&
        (this.backorderStatus == null ? productAdd.backorderStatus == null : this.backorderStatus.equals(productAdd.backorderStatus)) &&
        (this.minOrderQuantity == null ? productAdd.minOrderQuantity == null : this.minOrderQuantity.equals(productAdd.minOrderQuantity)) &&
        (this.maxOrderQuantity == null ? productAdd.maxOrderQuantity == null : this.maxOrderQuantity.equals(productAdd.maxOrderQuantity)) &&
        (this.weight == null ? productAdd.weight == null : this.weight.equals(productAdd.weight)) &&
        (this.weightUnit == null ? productAdd.weightUnit == null : this.weightUnit.equals(productAdd.weightUnit)) &&
        (this.width == null ? productAdd.width == null : this.width.equals(productAdd.width)) &&
        (this.height == null ? productAdd.height == null : this.height.equals(productAdd.height)) &&
        (this.length == null ? productAdd.length == null : this.length.equals(productAdd.length)) &&
        (this.dimensionsUnit == null ? productAdd.dimensionsUnit == null : this.dimensionsUnit.equals(productAdd.dimensionsUnit)) &&
        (this.barcode == null ? productAdd.barcode == null : this.barcode.equals(productAdd.barcode)) &&
        (this.upc == null ? productAdd.upc == null : this.upc.equals(productAdd.upc)) &&
        (this.ean == null ? productAdd.ean == null : this.ean.equals(productAdd.ean)) &&
        (this.isbn == null ? productAdd.isbn == null : this.isbn.equals(productAdd.isbn)) &&
        (this.gtin == null ? productAdd.gtin == null : this.gtin.equals(productAdd.gtin)) &&
        (this.mpn == null ? productAdd.mpn == null : this.mpn.equals(productAdd.mpn)) &&
        (this.asin == null ? productAdd.asin == null : this.asin.equals(productAdd.asin)) &&
        (this.productReference == null ? productAdd.productReference == null : this.productReference.equals(productAdd.productReference)) &&
        (this.harmonizedSystemCode == null ? productAdd.harmonizedSystemCode == null : this.harmonizedSystemCode.equals(productAdd.harmonizedSystemCode)) &&
        (this.countryOfOrigin == null ? productAdd.countryOfOrigin == null : this.countryOfOrigin.equals(productAdd.countryOfOrigin)) &&
        (this.manufacturer == null ? productAdd.manufacturer == null : this.manufacturer.equals(productAdd.manufacturer)) &&
        (this.manufacturerId == null ? productAdd.manufacturerId == null : this.manufacturerId.equals(productAdd.manufacturerId)) &&
        (this.manufacturerInfo == null ? productAdd.manufacturerInfo == null : this.manufacturerInfo.equals(productAdd.manufacturerInfo)) &&
        (this.brandName == null ? productAdd.brandName == null : this.brandName.equals(productAdd.brandName)) &&
        (this.imageUrl == null ? productAdd.imageUrl == null : this.imageUrl.equals(productAdd.imageUrl)) &&
        (this.imageName == null ? productAdd.imageName == null : this.imageName.equals(productAdd.imageName)) &&
        (this.additionalImageUrls == null ? productAdd.additionalImageUrls == null : this.additionalImageUrls.equals(productAdd.additionalImageUrls)) &&
        (this.files == null ? productAdd.files == null : this.files.equals(productAdd.files)) &&
        (this.sizeChart == null ? productAdd.sizeChart == null : this.sizeChart.equals(productAdd.sizeChart)) &&
        (this.relatedProductsIds == null ? productAdd.relatedProductsIds == null : this.relatedProductsIds.equals(productAdd.relatedProductsIds)) &&
        (this.upSellProductsIds == null ? productAdd.upSellProductsIds == null : this.upSellProductsIds.equals(productAdd.upSellProductsIds)) &&
        (this.crossSellProductsIds == null ? productAdd.crossSellProductsIds == null : this.crossSellProductsIds.equals(productAdd.crossSellProductsIds)) &&
        (this.attributeSetName == null ? productAdd.attributeSetName == null : this.attributeSetName.equals(productAdd.attributeSetName)) &&
        (this.attributeName == null ? productAdd.attributeName == null : this.attributeName.equals(productAdd.attributeName)) &&
        (this.searchKeywords == null ? productAdd.searchKeywords == null : this.searchKeywords.equals(productAdd.searchKeywords)) &&
        (this.tags == null ? productAdd.tags == null : this.tags.equals(productAdd.tags)) &&
        (this.materials == null ? productAdd.materials == null : this.materials.equals(productAdd.materials)) &&
        (this.certifications == null ? productAdd.certifications == null : this.certifications.equals(productAdd.certifications)) &&
        (this.specifics == null ? productAdd.specifics == null : this.specifics.equals(productAdd.specifics)) &&
        (this.availFrom == null ? productAdd.availFrom == null : this.availFrom.equals(productAdd.availFrom)) &&
        (this.spriceCreate == null ? productAdd.spriceCreate == null : this.spriceCreate.equals(productAdd.spriceCreate)) &&
        (this.spriceModified == null ? productAdd.spriceModified == null : this.spriceModified.equals(productAdd.spriceModified)) &&
        (this.spriceExpire == null ? productAdd.spriceExpire == null : this.spriceExpire.equals(productAdd.spriceExpire)) &&
        (this.createdAt == null ? productAdd.createdAt == null : this.createdAt.equals(productAdd.createdAt)) &&
        (this.autoRenew == null ? productAdd.autoRenew == null : this.autoRenew.equals(productAdd.autoRenew)) &&
        (this.whenMade == null ? productAdd.whenMade == null : this.whenMade.equals(productAdd.whenMade)) &&
        (this.metaTitle == null ? productAdd.metaTitle == null : this.metaTitle.equals(productAdd.metaTitle)) &&
        (this.metaKeywords == null ? productAdd.metaKeywords == null : this.metaKeywords.equals(productAdd.metaKeywords)) &&
        (this.metaDescription == null ? productAdd.metaDescription == null : this.metaDescription.equals(productAdd.metaDescription)) &&
        (this.url == null ? productAdd.url == null : this.url.equals(productAdd.url)) &&
        (this.seoUrl == null ? productAdd.seoUrl == null : this.seoUrl.equals(productAdd.seoUrl)) &&
        (this.taxClassId == null ? productAdd.taxClassId == null : this.taxClassId.equals(productAdd.taxClassId)) &&
        (this.taxable == null ? productAdd.taxable == null : this.taxable.equals(productAdd.taxable)) &&
        (this.salesTax == null ? productAdd.salesTax == null : this.salesTax.equals(productAdd.salesTax)) &&
        (this.condition == null ? productAdd.condition == null : this.condition.equals(productAdd.condition)) &&
        (this.conditionDescription == null ? productAdd.conditionDescription == null : this.conditionDescription.equals(productAdd.conditionDescription)) &&
        (this.allowDisplayCondition == null ? productAdd.allowDisplayCondition == null : this.allowDisplayCondition.equals(productAdd.allowDisplayCondition)) &&
        (this.paymentMethods == null ? productAdd.paymentMethods == null : this.paymentMethods.equals(productAdd.paymentMethods)) &&
        (this.paypalEmail == null ? productAdd.paypalEmail == null : this.paypalEmail.equals(productAdd.paypalEmail)) &&
        (this.shippingTemplateId == null ? productAdd.shippingTemplateId == null : this.shippingTemplateId.equals(productAdd.shippingTemplateId)) &&
        (this.shippingDetails == null ? productAdd.shippingDetails == null : this.shippingDetails.equals(productAdd.shippingDetails)) &&
        (this.isFreeShipping == null ? productAdd.isFreeShipping == null : this.isFreeShipping.equals(productAdd.isFreeShipping)) &&
        (this.deliveryCode == null ? productAdd.deliveryCode == null : this.deliveryCode.equals(productAdd.deliveryCode)) &&
        (this.deliveryType == null ? productAdd.deliveryType == null : this.deliveryType.equals(productAdd.deliveryType)) &&
        (this.deliveryTime == null ? productAdd.deliveryTime == null : this.deliveryTime.equals(productAdd.deliveryTime)) &&
        (this.deliveryOptionIds == null ? productAdd.deliveryOptionIds == null : this.deliveryOptionIds.equals(productAdd.deliveryOptionIds)) &&
        (this.packageDetails == null ? productAdd.packageDetails == null : this.packageDetails.equals(productAdd.packageDetails)) &&
        (this.logisticInfo == null ? productAdd.logisticInfo == null : this.logisticInfo.equals(productAdd.logisticInfo)) &&
        (this.listingDuration == null ? productAdd.listingDuration == null : this.listingDuration.equals(productAdd.listingDuration)) &&
        (this.listingType == null ? productAdd.listingType == null : this.listingType.equals(productAdd.listingType)) &&
        (this.returnAccepted == null ? productAdd.returnAccepted == null : this.returnAccepted.equals(productAdd.returnAccepted)) &&
        (this.sellerProfiles == null ? productAdd.sellerProfiles == null : this.sellerProfiles.equals(productAdd.sellerProfiles)) &&
        (this.auctionConfidentialityLevel == null ? productAdd.auctionConfidentialityLevel == null : this.auctionConfidentialityLevel.equals(productAdd.auctionConfidentialityLevel)) &&
        (this.bestOffer == null ? productAdd.bestOffer == null : this.bestOffer.equals(productAdd.bestOffer)) &&
        (this.productionPartnerIds == null ? productAdd.productionPartnerIds == null : this.productionPartnerIds.equals(productAdd.productionPartnerIds)) &&
        (this.marketplaceItemProperties == null ? productAdd.marketplaceItemProperties == null : this.marketplaceItemProperties.equals(productAdd.marketplaceItemProperties)) &&
        (this.clearCache == null ? productAdd.clearCache == null : this.clearCache.equals(productAdd.clearCache)) &&
        (this.viewedCount == null ? productAdd.viewedCount == null : this.viewedCount.equals(productAdd.viewedCount)) &&
        (this.orderedCount == null ? productAdd.orderedCount == null : this.orderedCount.equals(productAdd.orderedCount)) &&
        (this.shopSectionId == null ? productAdd.shopSectionId == null : this.shopSectionId.equals(productAdd.shopSectionId)) &&
        (this.returnPolicyId == null ? productAdd.returnPolicyId == null : this.returnPolicyId.equals(productAdd.returnPolicyId)) &&
        (this.personalizationDetails == null ? productAdd.personalizationDetails == null : this.personalizationDetails.equals(productAdd.personalizationDetails));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.model == null ? 0: this.model.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.price == null ? 0: this.price.hashCode());
    result = 31 * result + (this.sku == null ? 0: this.sku.hashCode());
    result = 31 * result + (this.shortDescription == null ? 0: this.shortDescription.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.visible == null ? 0: this.visible.hashCode());
    result = 31 * result + (this.categoryId == null ? 0: this.categoryId.hashCode());
    result = 31 * result + (this.categoriesIds == null ? 0: this.categoriesIds.hashCode());
    result = 31 * result + (this.productClass == null ? 0: this.productClass.hashCode());
    result = 31 * result + (this.productType == null ? 0: this.productType.hashCode());
    result = 31 * result + (this.isVirtual == null ? 0: this.isVirtual.hashCode());
    result = 31 * result + (this.downloadable == null ? 0: this.downloadable.hashCode());
    result = 31 * result + (this.isSupply == null ? 0: this.isSupply.hashCode());
    result = 31 * result + (this.availableForView == null ? 0: this.availableForView.hashCode());
    result = 31 * result + (this.availableForSale == null ? 0: this.availableForSale.hashCode());
    result = 31 * result + (this.storeId == null ? 0: this.storeId.hashCode());
    result = 31 * result + (this.storesIds == null ? 0: this.storesIds.hashCode());
    result = 31 * result + (this.langId == null ? 0: this.langId.hashCode());
    result = 31 * result + (this.oldPrice == null ? 0: this.oldPrice.hashCode());
    result = 31 * result + (this.specialPrice == null ? 0: this.specialPrice.hashCode());
    result = 31 * result + (this.wholesalePrice == null ? 0: this.wholesalePrice.hashCode());
    result = 31 * result + (this.costPrice == null ? 0: this.costPrice.hashCode());
    result = 31 * result + (this.fixedCostShippingPrice == null ? 0: this.fixedCostShippingPrice.hashCode());
    result = 31 * result + (this.tierPrices == null ? 0: this.tierPrices.hashCode());
    result = 31 * result + (this.groupPrices == null ? 0: this.groupPrices.hashCode());
    result = 31 * result + (this.buyitnowPrice == null ? 0: this.buyitnowPrice.hashCode());
    result = 31 * result + (this.reservePrice == null ? 0: this.reservePrice.hashCode());
    result = 31 * result + (this.quantity == null ? 0: this.quantity.hashCode());
    result = 31 * result + (this.inStock == null ? 0: this.inStock.hashCode());
    result = 31 * result + (this.manageStock == null ? 0: this.manageStock.hashCode());
    result = 31 * result + (this.warehouseId == null ? 0: this.warehouseId.hashCode());
    result = 31 * result + (this.backorderStatus == null ? 0: this.backorderStatus.hashCode());
    result = 31 * result + (this.minOrderQuantity == null ? 0: this.minOrderQuantity.hashCode());
    result = 31 * result + (this.maxOrderQuantity == null ? 0: this.maxOrderQuantity.hashCode());
    result = 31 * result + (this.weight == null ? 0: this.weight.hashCode());
    result = 31 * result + (this.weightUnit == null ? 0: this.weightUnit.hashCode());
    result = 31 * result + (this.width == null ? 0: this.width.hashCode());
    result = 31 * result + (this.height == null ? 0: this.height.hashCode());
    result = 31 * result + (this.length == null ? 0: this.length.hashCode());
    result = 31 * result + (this.dimensionsUnit == null ? 0: this.dimensionsUnit.hashCode());
    result = 31 * result + (this.barcode == null ? 0: this.barcode.hashCode());
    result = 31 * result + (this.upc == null ? 0: this.upc.hashCode());
    result = 31 * result + (this.ean == null ? 0: this.ean.hashCode());
    result = 31 * result + (this.isbn == null ? 0: this.isbn.hashCode());
    result = 31 * result + (this.gtin == null ? 0: this.gtin.hashCode());
    result = 31 * result + (this.mpn == null ? 0: this.mpn.hashCode());
    result = 31 * result + (this.asin == null ? 0: this.asin.hashCode());
    result = 31 * result + (this.productReference == null ? 0: this.productReference.hashCode());
    result = 31 * result + (this.harmonizedSystemCode == null ? 0: this.harmonizedSystemCode.hashCode());
    result = 31 * result + (this.countryOfOrigin == null ? 0: this.countryOfOrigin.hashCode());
    result = 31 * result + (this.manufacturer == null ? 0: this.manufacturer.hashCode());
    result = 31 * result + (this.manufacturerId == null ? 0: this.manufacturerId.hashCode());
    result = 31 * result + (this.manufacturerInfo == null ? 0: this.manufacturerInfo.hashCode());
    result = 31 * result + (this.brandName == null ? 0: this.brandName.hashCode());
    result = 31 * result + (this.imageUrl == null ? 0: this.imageUrl.hashCode());
    result = 31 * result + (this.imageName == null ? 0: this.imageName.hashCode());
    result = 31 * result + (this.additionalImageUrls == null ? 0: this.additionalImageUrls.hashCode());
    result = 31 * result + (this.files == null ? 0: this.files.hashCode());
    result = 31 * result + (this.sizeChart == null ? 0: this.sizeChart.hashCode());
    result = 31 * result + (this.relatedProductsIds == null ? 0: this.relatedProductsIds.hashCode());
    result = 31 * result + (this.upSellProductsIds == null ? 0: this.upSellProductsIds.hashCode());
    result = 31 * result + (this.crossSellProductsIds == null ? 0: this.crossSellProductsIds.hashCode());
    result = 31 * result + (this.attributeSetName == null ? 0: this.attributeSetName.hashCode());
    result = 31 * result + (this.attributeName == null ? 0: this.attributeName.hashCode());
    result = 31 * result + (this.searchKeywords == null ? 0: this.searchKeywords.hashCode());
    result = 31 * result + (this.tags == null ? 0: this.tags.hashCode());
    result = 31 * result + (this.materials == null ? 0: this.materials.hashCode());
    result = 31 * result + (this.certifications == null ? 0: this.certifications.hashCode());
    result = 31 * result + (this.specifics == null ? 0: this.specifics.hashCode());
    result = 31 * result + (this.availFrom == null ? 0: this.availFrom.hashCode());
    result = 31 * result + (this.spriceCreate == null ? 0: this.spriceCreate.hashCode());
    result = 31 * result + (this.spriceModified == null ? 0: this.spriceModified.hashCode());
    result = 31 * result + (this.spriceExpire == null ? 0: this.spriceExpire.hashCode());
    result = 31 * result + (this.createdAt == null ? 0: this.createdAt.hashCode());
    result = 31 * result + (this.autoRenew == null ? 0: this.autoRenew.hashCode());
    result = 31 * result + (this.whenMade == null ? 0: this.whenMade.hashCode());
    result = 31 * result + (this.metaTitle == null ? 0: this.metaTitle.hashCode());
    result = 31 * result + (this.metaKeywords == null ? 0: this.metaKeywords.hashCode());
    result = 31 * result + (this.metaDescription == null ? 0: this.metaDescription.hashCode());
    result = 31 * result + (this.url == null ? 0: this.url.hashCode());
    result = 31 * result + (this.seoUrl == null ? 0: this.seoUrl.hashCode());
    result = 31 * result + (this.taxClassId == null ? 0: this.taxClassId.hashCode());
    result = 31 * result + (this.taxable == null ? 0: this.taxable.hashCode());
    result = 31 * result + (this.salesTax == null ? 0: this.salesTax.hashCode());
    result = 31 * result + (this.condition == null ? 0: this.condition.hashCode());
    result = 31 * result + (this.conditionDescription == null ? 0: this.conditionDescription.hashCode());
    result = 31 * result + (this.allowDisplayCondition == null ? 0: this.allowDisplayCondition.hashCode());
    result = 31 * result + (this.paymentMethods == null ? 0: this.paymentMethods.hashCode());
    result = 31 * result + (this.paypalEmail == null ? 0: this.paypalEmail.hashCode());
    result = 31 * result + (this.shippingTemplateId == null ? 0: this.shippingTemplateId.hashCode());
    result = 31 * result + (this.shippingDetails == null ? 0: this.shippingDetails.hashCode());
    result = 31 * result + (this.isFreeShipping == null ? 0: this.isFreeShipping.hashCode());
    result = 31 * result + (this.deliveryCode == null ? 0: this.deliveryCode.hashCode());
    result = 31 * result + (this.deliveryType == null ? 0: this.deliveryType.hashCode());
    result = 31 * result + (this.deliveryTime == null ? 0: this.deliveryTime.hashCode());
    result = 31 * result + (this.deliveryOptionIds == null ? 0: this.deliveryOptionIds.hashCode());
    result = 31 * result + (this.packageDetails == null ? 0: this.packageDetails.hashCode());
    result = 31 * result + (this.logisticInfo == null ? 0: this.logisticInfo.hashCode());
    result = 31 * result + (this.listingDuration == null ? 0: this.listingDuration.hashCode());
    result = 31 * result + (this.listingType == null ? 0: this.listingType.hashCode());
    result = 31 * result + (this.returnAccepted == null ? 0: this.returnAccepted.hashCode());
    result = 31 * result + (this.sellerProfiles == null ? 0: this.sellerProfiles.hashCode());
    result = 31 * result + (this.auctionConfidentialityLevel == null ? 0: this.auctionConfidentialityLevel.hashCode());
    result = 31 * result + (this.bestOffer == null ? 0: this.bestOffer.hashCode());
    result = 31 * result + (this.productionPartnerIds == null ? 0: this.productionPartnerIds.hashCode());
    result = 31 * result + (this.marketplaceItemProperties == null ? 0: this.marketplaceItemProperties.hashCode());
    result = 31 * result + (this.clearCache == null ? 0: this.clearCache.hashCode());
    result = 31 * result + (this.viewedCount == null ? 0: this.viewedCount.hashCode());
    result = 31 * result + (this.orderedCount == null ? 0: this.orderedCount.hashCode());
    result = 31 * result + (this.shopSectionId == null ? 0: this.shopSectionId.hashCode());
    result = 31 * result + (this.returnPolicyId == null ? 0: this.returnPolicyId.hashCode());
    result = 31 * result + (this.personalizationDetails == null ? 0: this.personalizationDetails.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductAdd {\n");
    
    sb.append("  name: ").append(name).append("\n");
    sb.append("  model: ").append(model).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  price: ").append(price).append("\n");
    sb.append("  sku: ").append(sku).append("\n");
    sb.append("  shortDescription: ").append(shortDescription).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  visible: ").append(visible).append("\n");
    sb.append("  categoryId: ").append(categoryId).append("\n");
    sb.append("  categoriesIds: ").append(categoriesIds).append("\n");
    sb.append("  productClass: ").append(productClass).append("\n");
    sb.append("  productType: ").append(productType).append("\n");
    sb.append("  isVirtual: ").append(isVirtual).append("\n");
    sb.append("  downloadable: ").append(downloadable).append("\n");
    sb.append("  isSupply: ").append(isSupply).append("\n");
    sb.append("  availableForView: ").append(availableForView).append("\n");
    sb.append("  availableForSale: ").append(availableForSale).append("\n");
    sb.append("  storeId: ").append(storeId).append("\n");
    sb.append("  storesIds: ").append(storesIds).append("\n");
    sb.append("  langId: ").append(langId).append("\n");
    sb.append("  oldPrice: ").append(oldPrice).append("\n");
    sb.append("  specialPrice: ").append(specialPrice).append("\n");
    sb.append("  wholesalePrice: ").append(wholesalePrice).append("\n");
    sb.append("  costPrice: ").append(costPrice).append("\n");
    sb.append("  fixedCostShippingPrice: ").append(fixedCostShippingPrice).append("\n");
    sb.append("  tierPrices: ").append(tierPrices).append("\n");
    sb.append("  groupPrices: ").append(groupPrices).append("\n");
    sb.append("  buyitnowPrice: ").append(buyitnowPrice).append("\n");
    sb.append("  reservePrice: ").append(reservePrice).append("\n");
    sb.append("  quantity: ").append(quantity).append("\n");
    sb.append("  inStock: ").append(inStock).append("\n");
    sb.append("  manageStock: ").append(manageStock).append("\n");
    sb.append("  warehouseId: ").append(warehouseId).append("\n");
    sb.append("  backorderStatus: ").append(backorderStatus).append("\n");
    sb.append("  minOrderQuantity: ").append(minOrderQuantity).append("\n");
    sb.append("  maxOrderQuantity: ").append(maxOrderQuantity).append("\n");
    sb.append("  weight: ").append(weight).append("\n");
    sb.append("  weightUnit: ").append(weightUnit).append("\n");
    sb.append("  width: ").append(width).append("\n");
    sb.append("  height: ").append(height).append("\n");
    sb.append("  length: ").append(length).append("\n");
    sb.append("  dimensionsUnit: ").append(dimensionsUnit).append("\n");
    sb.append("  barcode: ").append(barcode).append("\n");
    sb.append("  upc: ").append(upc).append("\n");
    sb.append("  ean: ").append(ean).append("\n");
    sb.append("  isbn: ").append(isbn).append("\n");
    sb.append("  gtin: ").append(gtin).append("\n");
    sb.append("  mpn: ").append(mpn).append("\n");
    sb.append("  asin: ").append(asin).append("\n");
    sb.append("  productReference: ").append(productReference).append("\n");
    sb.append("  harmonizedSystemCode: ").append(harmonizedSystemCode).append("\n");
    sb.append("  countryOfOrigin: ").append(countryOfOrigin).append("\n");
    sb.append("  manufacturer: ").append(manufacturer).append("\n");
    sb.append("  manufacturerId: ").append(manufacturerId).append("\n");
    sb.append("  manufacturerInfo: ").append(manufacturerInfo).append("\n");
    sb.append("  brandName: ").append(brandName).append("\n");
    sb.append("  imageUrl: ").append(imageUrl).append("\n");
    sb.append("  imageName: ").append(imageName).append("\n");
    sb.append("  additionalImageUrls: ").append(additionalImageUrls).append("\n");
    sb.append("  files: ").append(files).append("\n");
    sb.append("  sizeChart: ").append(sizeChart).append("\n");
    sb.append("  relatedProductsIds: ").append(relatedProductsIds).append("\n");
    sb.append("  upSellProductsIds: ").append(upSellProductsIds).append("\n");
    sb.append("  crossSellProductsIds: ").append(crossSellProductsIds).append("\n");
    sb.append("  attributeSetName: ").append(attributeSetName).append("\n");
    sb.append("  attributeName: ").append(attributeName).append("\n");
    sb.append("  searchKeywords: ").append(searchKeywords).append("\n");
    sb.append("  tags: ").append(tags).append("\n");
    sb.append("  materials: ").append(materials).append("\n");
    sb.append("  certifications: ").append(certifications).append("\n");
    sb.append("  specifics: ").append(specifics).append("\n");
    sb.append("  availFrom: ").append(availFrom).append("\n");
    sb.append("  spriceCreate: ").append(spriceCreate).append("\n");
    sb.append("  spriceModified: ").append(spriceModified).append("\n");
    sb.append("  spriceExpire: ").append(spriceExpire).append("\n");
    sb.append("  createdAt: ").append(createdAt).append("\n");
    sb.append("  autoRenew: ").append(autoRenew).append("\n");
    sb.append("  whenMade: ").append(whenMade).append("\n");
    sb.append("  metaTitle: ").append(metaTitle).append("\n");
    sb.append("  metaKeywords: ").append(metaKeywords).append("\n");
    sb.append("  metaDescription: ").append(metaDescription).append("\n");
    sb.append("  url: ").append(url).append("\n");
    sb.append("  seoUrl: ").append(seoUrl).append("\n");
    sb.append("  taxClassId: ").append(taxClassId).append("\n");
    sb.append("  taxable: ").append(taxable).append("\n");
    sb.append("  salesTax: ").append(salesTax).append("\n");
    sb.append("  condition: ").append(condition).append("\n");
    sb.append("  conditionDescription: ").append(conditionDescription).append("\n");
    sb.append("  allowDisplayCondition: ").append(allowDisplayCondition).append("\n");
    sb.append("  paymentMethods: ").append(paymentMethods).append("\n");
    sb.append("  paypalEmail: ").append(paypalEmail).append("\n");
    sb.append("  shippingTemplateId: ").append(shippingTemplateId).append("\n");
    sb.append("  shippingDetails: ").append(shippingDetails).append("\n");
    sb.append("  isFreeShipping: ").append(isFreeShipping).append("\n");
    sb.append("  deliveryCode: ").append(deliveryCode).append("\n");
    sb.append("  deliveryType: ").append(deliveryType).append("\n");
    sb.append("  deliveryTime: ").append(deliveryTime).append("\n");
    sb.append("  deliveryOptionIds: ").append(deliveryOptionIds).append("\n");
    sb.append("  packageDetails: ").append(packageDetails).append("\n");
    sb.append("  logisticInfo: ").append(logisticInfo).append("\n");
    sb.append("  listingDuration: ").append(listingDuration).append("\n");
    sb.append("  listingType: ").append(listingType).append("\n");
    sb.append("  returnAccepted: ").append(returnAccepted).append("\n");
    sb.append("  sellerProfiles: ").append(sellerProfiles).append("\n");
    sb.append("  auctionConfidentialityLevel: ").append(auctionConfidentialityLevel).append("\n");
    sb.append("  bestOffer: ").append(bestOffer).append("\n");
    sb.append("  productionPartnerIds: ").append(productionPartnerIds).append("\n");
    sb.append("  marketplaceItemProperties: ").append(marketplaceItemProperties).append("\n");
    sb.append("  clearCache: ").append(clearCache).append("\n");
    sb.append("  viewedCount: ").append(viewedCount).append("\n");
    sb.append("  orderedCount: ").append(orderedCount).append("\n");
    sb.append("  shopSectionId: ").append(shopSectionId).append("\n");
    sb.append("  returnPolicyId: ").append(returnPolicyId).append("\n");
    sb.append("  personalizationDetails: ").append(personalizationDetails).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
