/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.ProductAddCertificationsInnerFilesInner;
import org.openapitools.client.model.ProductAddCertificationsInnerImagesInner;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ProductAddCertificationsInner {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("images")
  private List<ProductAddCertificationsInnerImagesInner> images = null;
  @SerializedName("files")
  private List<ProductAddCertificationsInnerFilesInner> files = null;

  /**
   * Certification ID
   **/
  @ApiModelProperty(required = true, value = "Certification ID")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   * Certification images
   **/
  @ApiModelProperty(value = "Certification images")
  public List<ProductAddCertificationsInnerImagesInner> getImages() {
    return images;
  }
  public void setImages(List<ProductAddCertificationsInnerImagesInner> images) {
    this.images = images;
  }

  /**
   * Certification files
   **/
  @ApiModelProperty(value = "Certification files")
  public List<ProductAddCertificationsInnerFilesInner> getFiles() {
    return files;
  }
  public void setFiles(List<ProductAddCertificationsInnerFilesInner> files) {
    this.files = files;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductAddCertificationsInner productAddCertificationsInner = (ProductAddCertificationsInner) o;
    return (this.id == null ? productAddCertificationsInner.id == null : this.id.equals(productAddCertificationsInner.id)) &&
        (this.images == null ? productAddCertificationsInner.images == null : this.images.equals(productAddCertificationsInner.images)) &&
        (this.files == null ? productAddCertificationsInner.files == null : this.files.equals(productAddCertificationsInner.files));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.images == null ? 0: this.images.hashCode());
    result = 31 * result + (this.files == null ? 0: this.files.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductAddCertificationsInner {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  images: ").append(images).append("\n");
    sb.append("  files: ").append(files).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
