/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ProductUpdateBatchPayloadInnerImagesInner {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("url")
  private String url = null;
  @SerializedName("label")
  private String label = null;
  @SerializedName("position")
  private Integer position = null;
  @SerializedName("type")
  private String type = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLabel() {
    return label;
  }
  public void setLabel(String label) {
    this.label = label;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getPosition() {
    return position;
  }
  public void setPosition(Integer position) {
    this.position = position;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductUpdateBatchPayloadInnerImagesInner productUpdateBatchPayloadInnerImagesInner = (ProductUpdateBatchPayloadInnerImagesInner) o;
    return (this.id == null ? productUpdateBatchPayloadInnerImagesInner.id == null : this.id.equals(productUpdateBatchPayloadInnerImagesInner.id)) &&
        (this.name == null ? productUpdateBatchPayloadInnerImagesInner.name == null : this.name.equals(productUpdateBatchPayloadInnerImagesInner.name)) &&
        (this.url == null ? productUpdateBatchPayloadInnerImagesInner.url == null : this.url.equals(productUpdateBatchPayloadInnerImagesInner.url)) &&
        (this.label == null ? productUpdateBatchPayloadInnerImagesInner.label == null : this.label.equals(productUpdateBatchPayloadInnerImagesInner.label)) &&
        (this.position == null ? productUpdateBatchPayloadInnerImagesInner.position == null : this.position.equals(productUpdateBatchPayloadInnerImagesInner.position)) &&
        (this.type == null ? productUpdateBatchPayloadInnerImagesInner.type == null : this.type.equals(productUpdateBatchPayloadInnerImagesInner.type));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.url == null ? 0: this.url.hashCode());
    result = 31 * result + (this.label == null ? 0: this.label.hashCode());
    result = 31 * result + (this.position == null ? 0: this.position.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductUpdateBatchPayloadInnerImagesInner {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  url: ").append(url).append("\n");
    sb.append("  label: ").append(label).append("\n");
    sb.append("  position: ").append(position).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
