/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.ProductOptionItem;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ProductOption {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("product_option_id")
  private String productOptionId = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("sort_order")
  private Integer sortOrder = null;
  @SerializedName("type")
  private String type = null;
  @SerializedName("required")
  private Boolean required = null;
  @SerializedName("available")
  private Boolean available = null;
  @SerializedName("used_in_combination")
  private Boolean usedInCombination = null;
  @SerializedName("option_items")
  private List<ProductOptionItem> optionItems = null;
  @SerializedName("additional_fields")
  private Object additionalFields = null;
  @SerializedName("custom_fields")
  private Object customFields = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getProductOptionId() {
    return productOptionId;
  }
  public void setProductOptionId(String productOptionId) {
    this.productOptionId = productOptionId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getSortOrder() {
    return sortOrder;
  }
  public void setSortOrder(Integer sortOrder) {
    this.sortOrder = sortOrder;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getRequired() {
    return required;
  }
  public void setRequired(Boolean required) {
    this.required = required;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getAvailable() {
    return available;
  }
  public void setAvailable(Boolean available) {
    this.available = available;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getUsedInCombination() {
    return usedInCombination;
  }
  public void setUsedInCombination(Boolean usedInCombination) {
    this.usedInCombination = usedInCombination;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<ProductOptionItem> getOptionItems() {
    return optionItems;
  }
  public void setOptionItems(List<ProductOptionItem> optionItems) {
    this.optionItems = optionItems;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getAdditionalFields() {
    return additionalFields;
  }
  public void setAdditionalFields(Object additionalFields) {
    this.additionalFields = additionalFields;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getCustomFields() {
    return customFields;
  }
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductOption productOption = (ProductOption) o;
    return (this.id == null ? productOption.id == null : this.id.equals(productOption.id)) &&
        (this.productOptionId == null ? productOption.productOptionId == null : this.productOptionId.equals(productOption.productOptionId)) &&
        (this.name == null ? productOption.name == null : this.name.equals(productOption.name)) &&
        (this.description == null ? productOption.description == null : this.description.equals(productOption.description)) &&
        (this.sortOrder == null ? productOption.sortOrder == null : this.sortOrder.equals(productOption.sortOrder)) &&
        (this.type == null ? productOption.type == null : this.type.equals(productOption.type)) &&
        (this.required == null ? productOption.required == null : this.required.equals(productOption.required)) &&
        (this.available == null ? productOption.available == null : this.available.equals(productOption.available)) &&
        (this.usedInCombination == null ? productOption.usedInCombination == null : this.usedInCombination.equals(productOption.usedInCombination)) &&
        (this.optionItems == null ? productOption.optionItems == null : this.optionItems.equals(productOption.optionItems)) &&
        (this.additionalFields == null ? productOption.additionalFields == null : this.additionalFields.equals(productOption.additionalFields)) &&
        (this.customFields == null ? productOption.customFields == null : this.customFields.equals(productOption.customFields));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.productOptionId == null ? 0: this.productOptionId.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.sortOrder == null ? 0: this.sortOrder.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.required == null ? 0: this.required.hashCode());
    result = 31 * result + (this.available == null ? 0: this.available.hashCode());
    result = 31 * result + (this.usedInCombination == null ? 0: this.usedInCombination.hashCode());
    result = 31 * result + (this.optionItems == null ? 0: this.optionItems.hashCode());
    result = 31 * result + (this.additionalFields == null ? 0: this.additionalFields.hashCode());
    result = 31 * result + (this.customFields == null ? 0: this.customFields.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductOption {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  productOptionId: ").append(productOptionId).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  sortOrder: ").append(sortOrder).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  required: ").append(required).append("\n");
    sb.append("  available: ").append(available).append("\n");
    sb.append("  usedInCombination: ").append(usedInCombination).append("\n");
    sb.append("  optionItems: ").append(optionItems).append("\n");
    sb.append("  additionalFields: ").append(additionalFields).append("\n");
    sb.append("  customFields: ").append(customFields).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
