/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.Shipment;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ResponseOrderShipmentListResult {
  
  @SerializedName("shipment_count")
  private Integer shipmentCount = null;
  @SerializedName("shipment")
  private List<Shipment> shipment = null;
  @SerializedName("additional_fields")
  private Object additionalFields = null;
  @SerializedName("custom_fields")
  private Object customFields = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getShipmentCount() {
    return shipmentCount;
  }
  public void setShipmentCount(Integer shipmentCount) {
    this.shipmentCount = shipmentCount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Shipment> getShipment() {
    return shipment;
  }
  public void setShipment(List<Shipment> shipment) {
    this.shipment = shipment;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getAdditionalFields() {
    return additionalFields;
  }
  public void setAdditionalFields(Object additionalFields) {
    this.additionalFields = additionalFields;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getCustomFields() {
    return customFields;
  }
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseOrderShipmentListResult responseOrderShipmentListResult = (ResponseOrderShipmentListResult) o;
    return (this.shipmentCount == null ? responseOrderShipmentListResult.shipmentCount == null : this.shipmentCount.equals(responseOrderShipmentListResult.shipmentCount)) &&
        (this.shipment == null ? responseOrderShipmentListResult.shipment == null : this.shipment.equals(responseOrderShipmentListResult.shipment)) &&
        (this.additionalFields == null ? responseOrderShipmentListResult.additionalFields == null : this.additionalFields.equals(responseOrderShipmentListResult.additionalFields)) &&
        (this.customFields == null ? responseOrderShipmentListResult.customFields == null : this.customFields.equals(responseOrderShipmentListResult.customFields));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.shipmentCount == null ? 0: this.shipmentCount.hashCode());
    result = 31 * result + (this.shipment == null ? 0: this.shipment.hashCode());
    result = 31 * result + (this.additionalFields == null ? 0: this.additionalFields.hashCode());
    result = 31 * result + (this.customFields == null ? 0: this.customFields.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseOrderShipmentListResult {\n");
    
    sb.append("  shipmentCount: ").append(shipmentCount).append("\n");
    sb.append("  shipment: ").append(shipment).append("\n");
    sb.append("  additionalFields: ").append(additionalFields).append("\n");
    sb.append("  customFields: ").append(customFields).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
