/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.math.BigDecimal;
import java.util.*;
import org.openapitools.client.model.A2CDateTime;
import org.openapitools.client.model.TaxClassRate;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ResponseTaxClassInfoResult {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("avail")
  private Boolean avail = null;
  @SerializedName("tax")
  private BigDecimal tax = null;
  @SerializedName("tax_type")
  private Integer taxType = null;
  @SerializedName("created_at")
  private A2CDateTime createdAt = null;
  @SerializedName("modified_at")
  private A2CDateTime modifiedAt = null;
  @SerializedName("tax_rates")
  private List<TaxClassRate> taxRates = null;
  @SerializedName("additional_fields")
  private Object additionalFields = null;
  @SerializedName("custom_fields")
  private Object customFields = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getAvail() {
    return avail;
  }
  public void setAvail(Boolean avail) {
    this.avail = avail;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getTax() {
    return tax;
  }
  public void setTax(BigDecimal tax) {
    this.tax = tax;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getTaxType() {
    return taxType;
  }
  public void setTaxType(Integer taxType) {
    this.taxType = taxType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public A2CDateTime getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(A2CDateTime createdAt) {
    this.createdAt = createdAt;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public A2CDateTime getModifiedAt() {
    return modifiedAt;
  }
  public void setModifiedAt(A2CDateTime modifiedAt) {
    this.modifiedAt = modifiedAt;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<TaxClassRate> getTaxRates() {
    return taxRates;
  }
  public void setTaxRates(List<TaxClassRate> taxRates) {
    this.taxRates = taxRates;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getAdditionalFields() {
    return additionalFields;
  }
  public void setAdditionalFields(Object additionalFields) {
    this.additionalFields = additionalFields;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getCustomFields() {
    return customFields;
  }
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseTaxClassInfoResult responseTaxClassInfoResult = (ResponseTaxClassInfoResult) o;
    return (this.id == null ? responseTaxClassInfoResult.id == null : this.id.equals(responseTaxClassInfoResult.id)) &&
        (this.name == null ? responseTaxClassInfoResult.name == null : this.name.equals(responseTaxClassInfoResult.name)) &&
        (this.avail == null ? responseTaxClassInfoResult.avail == null : this.avail.equals(responseTaxClassInfoResult.avail)) &&
        (this.tax == null ? responseTaxClassInfoResult.tax == null : this.tax.equals(responseTaxClassInfoResult.tax)) &&
        (this.taxType == null ? responseTaxClassInfoResult.taxType == null : this.taxType.equals(responseTaxClassInfoResult.taxType)) &&
        (this.createdAt == null ? responseTaxClassInfoResult.createdAt == null : this.createdAt.equals(responseTaxClassInfoResult.createdAt)) &&
        (this.modifiedAt == null ? responseTaxClassInfoResult.modifiedAt == null : this.modifiedAt.equals(responseTaxClassInfoResult.modifiedAt)) &&
        (this.taxRates == null ? responseTaxClassInfoResult.taxRates == null : this.taxRates.equals(responseTaxClassInfoResult.taxRates)) &&
        (this.additionalFields == null ? responseTaxClassInfoResult.additionalFields == null : this.additionalFields.equals(responseTaxClassInfoResult.additionalFields)) &&
        (this.customFields == null ? responseTaxClassInfoResult.customFields == null : this.customFields.equals(responseTaxClassInfoResult.customFields));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.avail == null ? 0: this.avail.hashCode());
    result = 31 * result + (this.tax == null ? 0: this.tax.hashCode());
    result = 31 * result + (this.taxType == null ? 0: this.taxType.hashCode());
    result = 31 * result + (this.createdAt == null ? 0: this.createdAt.hashCode());
    result = 31 * result + (this.modifiedAt == null ? 0: this.modifiedAt.hashCode());
    result = 31 * result + (this.taxRates == null ? 0: this.taxRates.hashCode());
    result = 31 * result + (this.additionalFields == null ? 0: this.additionalFields.hashCode());
    result = 31 * result + (this.customFields == null ? 0: this.customFields.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseTaxClassInfoResult {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  avail: ").append(avail).append("\n");
    sb.append("  tax: ").append(tax).append("\n");
    sb.append("  taxType: ").append(taxType).append("\n");
    sb.append("  createdAt: ").append(createdAt).append("\n");
    sb.append("  modifiedAt: ").append(modifiedAt).append("\n");
    sb.append("  taxRates: ").append(taxRates).append("\n");
    sb.append("  additionalFields: ").append(additionalFields).append("\n");
    sb.append("  customFields: ").append(customFields).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
