/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.StoreAttributeAttributeSet;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ResponseAttributeAttributesetListResult {
  
  @SerializedName("attribute_set")
  private List<StoreAttributeAttributeSet> attributeSet = null;
  @SerializedName("additional_fields")
  private Object additionalFields = null;
  @SerializedName("custom_fields")
  private Object customFields = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<StoreAttributeAttributeSet> getAttributeSet() {
    return attributeSet;
  }
  public void setAttributeSet(List<StoreAttributeAttributeSet> attributeSet) {
    this.attributeSet = attributeSet;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getAdditionalFields() {
    return additionalFields;
  }
  public void setAdditionalFields(Object additionalFields) {
    this.additionalFields = additionalFields;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getCustomFields() {
    return customFields;
  }
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseAttributeAttributesetListResult responseAttributeAttributesetListResult = (ResponseAttributeAttributesetListResult) o;
    return (this.attributeSet == null ? responseAttributeAttributesetListResult.attributeSet == null : this.attributeSet.equals(responseAttributeAttributesetListResult.attributeSet)) &&
        (this.additionalFields == null ? responseAttributeAttributesetListResult.additionalFields == null : this.additionalFields.equals(responseAttributeAttributesetListResult.additionalFields)) &&
        (this.customFields == null ? responseAttributeAttributesetListResult.customFields == null : this.customFields.equals(responseAttributeAttributesetListResult.customFields));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.attributeSet == null ? 0: this.attributeSet.hashCode());
    result = 31 * result + (this.additionalFields == null ? 0: this.additionalFields.hashCode());
    result = 31 * result + (this.customFields == null ? 0: this.customFields.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseAttributeAttributesetListResult {\n");
    
    sb.append("  attributeSet: ").append(attributeSet).append("\n");
    sb.append("  additionalFields: ").append(additionalFields).append("\n");
    sb.append("  customFields: ").append(customFields).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
