/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.CatalogPriceRule;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ResponseCartCatalogPriceRulesListResult {
  
  @SerializedName("catalog_price_rules_count")
  private Integer catalogPriceRulesCount = null;
  @SerializedName("catalog_price_rules")
  private List<CatalogPriceRule> catalogPriceRules = null;
  @SerializedName("additional_fields")
  private Object additionalFields = null;
  @SerializedName("custom_fields")
  private Object customFields = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getCatalogPriceRulesCount() {
    return catalogPriceRulesCount;
  }
  public void setCatalogPriceRulesCount(Integer catalogPriceRulesCount) {
    this.catalogPriceRulesCount = catalogPriceRulesCount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<CatalogPriceRule> getCatalogPriceRules() {
    return catalogPriceRules;
  }
  public void setCatalogPriceRules(List<CatalogPriceRule> catalogPriceRules) {
    this.catalogPriceRules = catalogPriceRules;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getAdditionalFields() {
    return additionalFields;
  }
  public void setAdditionalFields(Object additionalFields) {
    this.additionalFields = additionalFields;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getCustomFields() {
    return customFields;
  }
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseCartCatalogPriceRulesListResult responseCartCatalogPriceRulesListResult = (ResponseCartCatalogPriceRulesListResult) o;
    return (this.catalogPriceRulesCount == null ? responseCartCatalogPriceRulesListResult.catalogPriceRulesCount == null : this.catalogPriceRulesCount.equals(responseCartCatalogPriceRulesListResult.catalogPriceRulesCount)) &&
        (this.catalogPriceRules == null ? responseCartCatalogPriceRulesListResult.catalogPriceRules == null : this.catalogPriceRules.equals(responseCartCatalogPriceRulesListResult.catalogPriceRules)) &&
        (this.additionalFields == null ? responseCartCatalogPriceRulesListResult.additionalFields == null : this.additionalFields.equals(responseCartCatalogPriceRulesListResult.additionalFields)) &&
        (this.customFields == null ? responseCartCatalogPriceRulesListResult.customFields == null : this.customFields.equals(responseCartCatalogPriceRulesListResult.customFields));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.catalogPriceRulesCount == null ? 0: this.catalogPriceRulesCount.hashCode());
    result = 31 * result + (this.catalogPriceRules == null ? 0: this.catalogPriceRules.hashCode());
    result = 31 * result + (this.additionalFields == null ? 0: this.additionalFields.hashCode());
    result = 31 * result + (this.customFields == null ? 0: this.customFields.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseCartCatalogPriceRulesListResult {\n");
    
    sb.append("  catalogPriceRulesCount: ").append(catalogPriceRulesCount).append("\n");
    sb.append("  catalogPriceRules: ").append(catalogPriceRules).append("\n");
    sb.append("  additionalFields: ").append(additionalFields).append("\n");
    sb.append("  customFields: ").append(customFields).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
