/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.OrderFinancialStatusList200ResponseResultOrderFinancialStatusesInner;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ReturnReasonList200ResponseResult {
  
  @SerializedName("return_reasons")
  private List<OrderFinancialStatusList200ResponseResultOrderFinancialStatusesInner> returnReasons = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<OrderFinancialStatusList200ResponseResultOrderFinancialStatusesInner> getReturnReasons() {
    return returnReasons;
  }
  public void setReturnReasons(List<OrderFinancialStatusList200ResponseResultOrderFinancialStatusesInner> returnReasons) {
    this.returnReasons = returnReasons;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReturnReasonList200ResponseResult returnReasonList200ResponseResult = (ReturnReasonList200ResponseResult) o;
    return (this.returnReasons == null ? returnReasonList200ResponseResult.returnReasons == null : this.returnReasons.equals(returnReasonList200ResponseResult.returnReasons));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.returnReasons == null ? 0: this.returnReasons.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReturnReasonList200ResponseResult {\n");
    
    sb.append("  returnReasons: ").append(returnReasons).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
