/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class WebhookCount200ResponseResult {
  
  @SerializedName("webhook_count")
  private Integer webhookCount = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getWebhookCount() {
    return webhookCount;
  }
  public void setWebhookCount(Integer webhookCount) {
    this.webhookCount = webhookCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookCount200ResponseResult webhookCount200ResponseResult = (WebhookCount200ResponseResult) o;
    return (this.webhookCount == null ? webhookCount200ResponseResult.webhookCount == null : this.webhookCount.equals(webhookCount200ResponseResult.webhookCount));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.webhookCount == null ? 0: this.webhookCount.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookCount200ResponseResult {\n");
    
    sb.append("  webhookCount: ").append(webhookCount).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
