/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class WebhookEvents200ResponseResultEventsInner {
  
  @SerializedName("webhook_name")
  private String webhookName = null;
  @SerializedName("entity")
  private String entity = null;
  @SerializedName("action")
  private String action = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getWebhookName() {
    return webhookName;
  }
  public void setWebhookName(String webhookName) {
    this.webhookName = webhookName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEntity() {
    return entity;
  }
  public void setEntity(String entity) {
    this.entity = entity;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAction() {
    return action;
  }
  public void setAction(String action) {
    this.action = action;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookEvents200ResponseResultEventsInner webhookEvents200ResponseResultEventsInner = (WebhookEvents200ResponseResultEventsInner) o;
    return (this.webhookName == null ? webhookEvents200ResponseResultEventsInner.webhookName == null : this.webhookName.equals(webhookEvents200ResponseResultEventsInner.webhookName)) &&
        (this.entity == null ? webhookEvents200ResponseResultEventsInner.entity == null : this.entity.equals(webhookEvents200ResponseResultEventsInner.entity)) &&
        (this.action == null ? webhookEvents200ResponseResultEventsInner.action == null : this.action.equals(webhookEvents200ResponseResultEventsInner.action));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.webhookName == null ? 0: this.webhookName.hashCode());
    result = 31 * result + (this.entity == null ? 0: this.entity.hashCode());
    result = 31 * result + (this.action == null ? 0: this.action.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookEvents200ResponseResultEventsInner {\n");
    
    sb.append("  webhookName: ").append(webhookName).append("\n");
    sb.append("  entity: ").append(entity).append("\n");
    sb.append("  action: ").append(action).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
