/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.WebhookEvents200ResponseResultEventsInner;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class WebhookEvents200ResponseResult {
  
  @SerializedName("events")
  private List<WebhookEvents200ResponseResultEventsInner> events = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<WebhookEvents200ResponseResultEventsInner> getEvents() {
    return events;
  }
  public void setEvents(List<WebhookEvents200ResponseResultEventsInner> events) {
    this.events = events;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookEvents200ResponseResult webhookEvents200ResponseResult = (WebhookEvents200ResponseResult) o;
    return (this.events == null ? webhookEvents200ResponseResult.events == null : this.events.equals(webhookEvents200ResponseResult.events));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.events == null ? 0: this.events.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookEvents200ResponseResult {\n");
    
    sb.append("  events: ").append(events).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
