name: Update android-sdk SDK

on:
  # Запускатися раз на тиждень (у неділю о 00:00 за UTC)
  schedule:
    - cron: '0 0 * * 0'
  # Додатково, щоб мати можливість запустити вручну
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_android_sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download android.tgz
        run: |
          curl -L -o android.tgz https://app.api2cart.com/sdk/openapi/android.tgz

      # Розпаковуємо, видаляючи 1 рівень (папку android)
      - name: Extract android.tgz
        run: |
          tar -xzf android.tgz --strip-components=1

      - name: Commit changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update android SDK [skip ci]"
          git push
